#!/bin/sh
#
# script for compiling and installing YAP under msys. Uses a mingw64
# compiler, msys shell and nsis to do the installing
# Please read the script before trying to execute it.
# Legal arguments for the script are
#  'threads' - enable threads
#  'no_threads',
#  '32', '64'  - compile for 32 or 64 bit architecture.
# By default threads are turned off and we use 64 bits.
#
# please check if you have gcc 64 bits in your path and a clone
# of msys shell like smartgit:
#
# http://sourceforge.net/projects/mingwbuilds/
#   PS: don't install in the default location.
#   mingw should avoid space in its directory,
#   it freaks winres out.
# http://nsis.sourceforge.net/Main_Page
#
#
YHOME=/y/vsc
VERSION=6.3.4
#cross-compiler for OSX, see http://mxe.cc/
#notice that OSX does not allow WIN64 emulation (wine64)
MXE=$HOME/Yap/mxe/usr
# by default, compile without threads
THREADS=no
# use 64 bits
ABI=64

SRC=/c/cygwin/Yap/yap-6.3
#SRC=/l/work/noth/git
#SRC_WIN=L:\\work\\noth\\git
#SRC="$HOME"/git/yap-6.3
TARGET=/c/Yap64
NSIS="/c/Program Files (x86)/NSIS/makensis"
# by default, ""
PREFIX_CMD=wine

I=$#
while test $I -gt 0
do
  if test $1 = threads
  then
    THREADS=yes
  elif test $1 = no_threads
  then
    THREADS=no
  elif test $1 = 32
  then
    ABI=32
  elif test $1 = 64
  then
    ABI=64
  else
    echo "received \"$1\", should be one of threads, no_threads, 32, 64"
  fi
  I=$(( $I - 1 ))
done

# srcdir comes from here, please avoid relative paths
CONFIGURE="$SRC"/configure
DEBUG=" --enable-debug-yap --enable-low-level-tracer"

# debugging setup
do_compile=true
do_install=true

# HOME WIN64 configuration

# DOCS_DIR=/l/work/noth/yapdocs
DOCS_DIR="$YHOME"/Yap/bins/threads

if test "$THREADS" = yes; then
  FULL_VERSION="$VERSION"-threads
else
  FULL_VERSION="$VERSION"
fi                                                           

if test $ABI = 64; then
  BUILD=/c/cygwin/Yap/mingw"$ABI"
  #GCC_DIR=/l/Work/noth/mingw-w64/x86_64-4.9.0-posix-seh-rt_v3-rev1/mingw64
  case $( uname ) in
    *Darwin*)
     GCC_DIR="$MXE"
     HOST="x86_64-w64-mingw32"
     LIB_PATH="$MXE"/"$HOST"/lib
     ;;
    *MINGW64*)
     GCC_DIR=/c/TDM-GCC-64
     HOST="x86_64-w64-mingw32"
     LIB_PATH="$GCC_DIR"/"$HOST"/lib
     ;;
  esac
  # ok.
  # BDD compiler package. Get version that compiles on Windows from Vitor!
  #  GMP=/l/Work/noth/msys/1.0/local
  GMP=/c/msys64/usr/win64
  CUDD=/c/cygwin/Yap/cudd-2.5.0-mingw64
  GECODE=no  # "/c/Program Files/Gecode"
  JAVA="$( echo /c/Program\ Files/Java/jdk* )"
  PYTHON="/c/Python33-64"
  R="$( echo /c/Program\ Files/R/R-*/bin/x64 )"

fi

# HOME WIN32 configuration
if test $ABI = 32; then
  ABI=32
  case $( uname ) in
    *Darwin*)
    #use mxe as a cross compiler
    GCC_DIR="$MXE"/bin
    PATH="$GCC_DIR":"$PATH"
    HOST="i686-pc-mingw32"
    LIB_PATH="$MXE"/"$HOST"/lib
    GECODE=no # install only allows one of 32 or 64 bits
    GMP=yes
    JAVA=no
    PYTHON=no
    REAL=no
    ;;
  esac

  case $( uname ) in
    *Darwin*)
     GCC_DIR="$MXE"
     HOST="x86_64-w64-mingw32"
     LIB_PATH="$MXE"/"$HOST"/lib
     ;;
    *MINGW64*)
     GCC_DIR=/c/TDM-GCC-64
     HOST="x86_64-w64-mingw32"
     LIB_PATH="$GCC_DIR"/"$HOST"/lib
     ;;
  esac
  # ok.
  # BDD compiler package. Get version that compiles on Windows from Vitor!
  #  GMP=/l/Work/noth/msys/1.0/local
  GMP=/c/msys64/usr/win32
  CUDD=/c/cygwin/Yap/cudd-2.5.0-mingw32
  GECODE=no  # "/c/Program Files/Gecode"
  JAVA="$( echo /c/Program\ Files\ */Java/jdk* )"
  PYTHON="/c/Python27"
  R="$( echo /c/Program\ Files/R/R-*/bin/i* )"
  HOST+=" --enable-abi=32"

fi

export PATH="$GCC_DIR"/bin:"$PATH"
# echo "gcc= " $GCC_DIR
# echo "host= " $HOST
if test x"$JAVA" != xno
then
  export PATH="$PATH":"$JAVA"/bin
fi
if test x"$PYTHON" != xno
then
  export PATH="$PATH":"$PYTHON"/"python.exe"
fi
if test x"$R" != xno
then
    export PATH="$PATH":"$R"
fi

if test ${THREADS} = yes
then
  cp "$LIB_PATH"/libwinpthread-1.dll .
  cp libwinpthread-1.dll pthreadGC2.dll
fi


if test $CUDD != no
then
  BDDLIB="yes"
  CPLINT="yes"
else
  BDDLIB="no"
  CPLINT="no"
fi

if test x"$GECODE" != xno
then
  export PATH="$PATH":"$GECODE"/bin
fi

if test "$JAVA" = yes
then
  export PATH="$PATH":"$JAVA"/bin
fi

if test "$PYTHON" = yes
then
  export PATH="$PATH":"$PYTHON"
fi

if test x"$R"  != xno
then
  if test $ABI = 32; then
    R_ABI=i386
  else
    R_ABI=x64
  fi
  export PATH="$PATH":"$R"
fi

if test do_compile = true
then
   make distclean
fi

export INSTALL_SH=$SRC/yap-6.3/install.sh
# avoid using relative paths
if test "$do_compile" = true; then
  BUILD=/c/cygwin/Yap/mingw"$ABI"
  mkdir -p  "$BUILD"
#  /bin/rm -rf "$BUILD"/*
  "$CONFIGURE" --host="$HOST" \
   --prefix="$TARGET"  $DEBUG\
     --with-R="$R" \
       --with-java="$JAVA" \
         --with-gmp="$GMP" \
           --with-python="$PYTHON" \
             --with-cudd="$CUDD" --enable-bddlib="$BDDLIB" --with-cplint="$CPLINT" \
               --with-gecode="$GECODE" \
                 --enable-threads="$THREADS"  --enable-pthread-locking

 make #-j 4 install
fi
if test "$do_install" = true; then
  if test $ABI = 64; then
    cp $DOCS_DIR/*html $TARGET/share/doc/Yap
    cp $DOCS_DIR/*pdf $TARGET/share/doc/Yap
    "$NSIS" -DREGKEY=SOFTWARE\\YAP\\Prolog64 \
      -DROOTDIR=$TARGET \
        -DABI="$ABI" \
          -DVERSION="$FULL_VERSION" \
            -DOPTIONS="$SRC_WIN\\misc\\options.ini" \
              -DOUT_DIR=".." -D"WIN64=1" \
                -NOCD $SRC/yap-6.3/misc/Yap.nsi
  else
    cp $DOCS_DIR/*html $TARGET/share/doc/Yap
    cp $DOCS_DIR/*pdf $TARGET/share/doc/Yap
    "$NSIS" -DREGKEY=SOFTWARE\\YAP\\Prolog \
      -DROOTDIR=$TARGET \
        -DABI="$ABI" \
          -DVERSION="$FULL_VERSION" \
            -DOPTIONS="$SRC_WIN\\misc\\options.ini" \
              -DOUT_DIR=".." \
                -NOCD $SRC/yap-6.3/misc/Yap.nsi
  fi
fi
