# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

query <- function(p_name, p_module, sexp) {
    .Call(`_yap4r_query`, p_name, p_module, sexp)
}

next <- function() {
    .Call(`_yap4r_next`)
}

cut <- function() {
    .Call(`_yap4r_cut`)
}

ask <- function(i) {
    .Call(`_yap4r_ask`, i)
}

