

/*--------------------------------------------------------------------------
* This file is autogenerated from config.h.in
* during the cmake configuration of your project. If you need to make changes
* edit the original file NOT THIS FILE.
 * --------------------------------------------------------------------------*/
 #ifndef CONFIG_H
 #define CONFIG_H

 /* config.h.in.  Generated from configure.in by autoheader.  */
 #define SYSTEM_OPTIONS  "${YAP_SYSTEM_OPTIONS}"

/* Define if building universal (internal helper macro) */
#ifndef AC_APPLE_UNIVERSAL_BUILD
#cmakedefine AC_APPLE_UNIVERSAL_BUILD "${AC_APPLE_UNIVERSAL_BUILD}"
#endif

/* Are we compiling with support for depth limitT? */
#ifndef DEPTH_LIMIT
#define DEPTH_LIMIT 1
#endif

/* Are we compiling with inlined emulator instructionsT? */
#ifndef USE_THREADED_CODE
#define USE_THREADED_CODE 1
#endif

/* Are we compiling with support for TABLINGtT? */
#ifndef TABLING
#define TABLING 1
#endif

/* Are we compiling with support for WAM level tracing? */
#ifndef LOW_LEVEL_TRACER
#define LOW_LEVEL_TRACER 1
#endif

/* Are we compiling with support for threads? */
#ifndef THREADS
#cmakedefine THREADS  "$YAP_THREADS"
#endif

/* Are we compiling with support for clause just-in-time compilationT? */
#ifndef YAP_JIT
#cmakedefine YAP_JIT  "$YAP_JIT"
#endif

/* longs should be in addresses that are multiple of four. */
#ifndef ALIGN_LONGS
#define ALIGN_LONGS 1
#endif

/* size in bits of words. */
#ifndef BITNESS
#define BITNESS "${bitness}"
#endif

/* if fflush(NULL) clobbers input pipes1 */
#ifndef BROKEN_FFLUSH_NULL
#cmakedefine BROKEN_FFLUSH_NULL "${BROKEN_FFLUSH_NULL}"
#endif



/* size of a cell in bytes. */
#ifndef CELLSIZE
#define CELLSIZE ${CELLSIZE}
#endif

/* c-compiler used */
#ifndef C_CC
#define C_CC "${CMAKE_C_COMPILER}"
#endif

/* compilation flags */
#ifndef C_CFLAGS
#define C_CFLAGS "${CFLAGS_EXPORT} ${CMAKE_C_FLAGS} ${FLAGS} ${LANGUAGE_COMPILE_FLAGS}"
#endif

/* linking flags */
#ifndef C_LDFLAGS
#define C_LDFLAGS "${LINK_FLAGS} ${LINK_LIBRARIES}"
#endif

/* libs for linking with DLLs */
#ifndef C_LIBPLSO
#define C_LIBPLSO "${CMAKE_SHARED_LINKER_FLAGS} ${LINK_FLAGS} ${LINK_LIBRARIES}"
#endif

/* main libs for YAP */
#ifndef C_LIBS
#define C_LIBS "${EXTRALIBS}"
#endif

/* IEEE floating-point, basically everyone except old VAXEN */
#ifndef FFIEEE
#define FFIEEE 1
#endif

/* old HP-UX VM magic, should be irrelevant now */
#ifndef FORCE_SECOND_QUADRANT
#cmakedefine FORCE_SECOND_QUADRANT "${FORCE_SECOND_QUADRANT}"
#endif

/* use Barts idea of allocating extra memory,
   probbly better to use two bits on 64bit machines
*/
#ifndef GC_NO_TAGS
#define GC_NO_TAGS 1
#endif

/* Define if gethostname() is provided */
#ifndef HAS_GETHOSTNAME
#cmakedefine HAS_GETHOSTNAME "${HAS_GETHOSTNAME}"
#endif

/* Define to 1 if you have the `access' function. */
#ifndef HAVE_ACCESS
#cmakedefine HAVE_ACCESS ${HAVE_ACCESS}
#endif

/* Define to 1 if you have the `acosh' function. */
#ifndef HAVE_ACOSH
#cmakedefine HAVE_ACOSH ${HAVE_ACOSH}
#endif

/* Define to 1 if you have the `add_history' function. */
#ifndef HAVE_ADD_HISTORY
#define HAVE_ADD_HISTORY ${HAVE_ADD_HISTORY}
#endif

/* Define to 1 if you have the `alarm' function. */
#ifndef HAVE_ALARM
#cmakedefine HAVE_ALARM ${HAVE_ALARM}
#endif

/* Define to 1 if you have the `alloca' function. */
#ifndef HAVE_ALLOCA
#cmakedefine HAVE_ALLOCA ${HAVE_ALLOCA}
#endif

/* Define to 1 if you have the <alloca.h> header file. */
#ifndef HAVE_ALLOCA_H
#cmakedefine HAVE_ALLOCA_H ${HAVE_ALLOCA_H}
#endif

/* Define to 1 if you have <archive.h>. */
#ifndef HAVE_ARCHIVE_H
#cmakedefine HAVE_ARCHIVE_H ${HAVE_ARCHIVE_H}
#endif

/* Define to 1 if you have the `archive_read_support_compression_bzip2'
function. */
#ifndef HAVE_ARCHIVE_READ_SUPPORT_COMPRESSION_BZIP2
#cmakedefine HAVE_ARCHIVE_READ_SUPPORT_COMPRESSION_BZIP2 ${HAVE_ARCHIVE_READ_SUPPORT_COMPRESSION_BZIP2}
#endif

/* Define to 1 if you have the `archive_read_support_compression_compress'
function. */
#ifndef HAVE_ARCHIVE_READ_SUPPORT_COMPRESSION_COMPRESS
#cmakedefine HAVE_ARCHIVE_READ_SUPPORT_COMPRESSION_COMPRESS ${HAVE_ARCHIVE_READ_SUPPORT_COMPRESSION_COMPRESS}
#endif

/* Define to 1 if you have the `archive_read_support_compression_gzip'
function. */
#ifndef HAVE_ARCHIVE_READ_SUPPORT_COMPRESSION_GZIP
#cmakedefine HAVE_ARCHIVE_READ_SUPPORT_COMPRESSION_GZIP ${HAVE_ARCHIVE_READ_SUPPORT_COMPRESSION_GZIP}
#endif

/* Define to 1 if you have the `archive_read_support_compression_lzma'
function. */
#ifndef HAVE_ARCHIVE_READ_SUPPORT_COMPRESSION_LZMA
#cmakedefine HAVE_ARCHIVE_READ_SUPPORT_COMPRESSION_LZMA ${HAVE_ARCHIVE_READ_SUPPORT_COMPRESSION_LZMA}
#endif

/* Define to 1 if you have the `archive_read_support_compression_none'
function. */
#ifndef HAVE_ARCHIVE_READ_SUPPORT_COMPRESSION_NONE
#cmakedefine HAVE_ARCHIVE_READ_SUPPORT_COMPRESSION_NONE ${HAVE_ARCHIVE_READ_SUPPORT_COMPRESSION_NONE}
#endif

/* Define to 1 if you have the `archive_read_support_compression_xz' function.
*/
#ifndef HAVE_ARCHIVE_READ_SUPPORT_COMPRESSION_XZ
#cmakedefine HAVE_ARCHIVE_READ_SUPPORT_COMPRESSION_XZ ${HAVE_ARCHIVE_READ_SUPPORT_COMPRESSION_XZ}
#endif

/* Define to 1 if you have the `archive_read_support_format_ar' function. */
#ifndef HAVE_ARCHIVE_READ_SUPPORT_FORMAT_AR
#cmakedefine HAVE_ARCHIVE_READ_SUPPORT_FORMAT_AR ${HAVE_ARCHIVE_READ_SUPPORT_FORMAT_AR}
#endif

/* Define to 1 if you have the `archive_read_support_format_cpio' function. */
#ifndef HAVE_ARCHIVE_READ_SUPPORT_FORMAT_CPIO
#cmakedefine HAVE_ARCHIVE_READ_SUPPORT_FORMAT_CPIO ${HAVE_ARCHIVE_READ_SUPPORT_FORMAT_CPIO}
#endif

/* Define to 1 if you have the `archive_read_support_format_empty' function.
*/
#ifndef HAVE_ARCHIVE_READ_SUPPORT_FORMAT_EMPTY
#cmakedefine HAVE_ARCHIVE_READ_SUPPORT_FORMAT_EMPTY ${HAVE_ARCHIVE_READ_SUPPORT_FORMAT_EMPTY}
#endif

/* Define to 1 if you have the `archive_read_support_format_iso9660' function.
*/
#ifndef HAVE_ARCHIVE_READ_SUPPORT_FORMAT_ISO9660
#cmakedefine HAVE_ARCHIVE_READ_SUPPORT_FORMAT_ISO9660 ${HAVE_ARCHIVE_READ_SUPPORT_FORMAT_ISO9660}
#endif

/* Define to 1 if you have the `archive_read_support_format_mtree' function.
*/
#ifndef HAVE_ARCHIVE_READ_SUPPORT_FORMAT_MTREE
#cmakedefine HAVE_ARCHIVE_READ_SUPPORT_FORMAT_MTREE ${HAVE_ARCHIVE_READ_SUPPORT_FORMAT_MTREE}
#endif

/* Define to 1 if you have the `archive_read_support_format_raw' function. */
#ifndef HAVE_ARCHIVE_READ_SUPPORT_FORMAT_RAW
#cmakedefine HAVE_ARCHIVE_READ_SUPPORT_FORMAT_RAW ${HAVE_ARCHIVE_READ_SUPPORT_FORMAT_RAW}
#endif

/* Define to 1 if you have the `archive_read_support_format_tar' function. */
#ifndef HAVE_ARCHIVE_READ_SUPPORT_FORMAT_TAR
#cmakedefine HAVE_ARCHIVE_READ_SUPPORT_FORMAT_TAR ${HAVE_ARCHIVE_READ_SUPPORT_FORMAT_TAR}
#endif

/* Define to 1 if you have the `archive_read_support_format_zip' function. */
#ifndef HAVE_ARCHIVE_READ_SUPPORT_FORMAT_ZIP
#cmakedefine HAVE_ARCHIVE_READ_SUPPORT_FORMAT_ZIP ${HAVE_ARCHIVE_READ_SUPPORT_FORMAT_ZIP}
#endif

/* Define to 1 if you have the <arpa/inet.h> header file. */
#ifndef HAVE_ARPA_INET_H
#cmakedefine HAVE_ARPA_INET_H ${HAVE_ARPA_INET_H}
#endif

/* Define to 1 if you have the `asinh' function. */
#ifndef HAVE_ASINH
#cmakedefine HAVE_ASINH ${HAVE_ASINH}
#endif

/* Define to 1 if you have the `atanh' function. */
#ifndef HAVE_ATANH
#cmakedefine HAVE_ATANH ${HAVE_ATANH}
#endif

/* Define to 1 if you have the `basename' function. */
#ifndef HAVE_BASENAME
#cmakedefine HAVE_BASENAME ${HAVE_BASENAME}
#endif

/* Define to 1 if you have the `basename' function. */
#ifndef HAVE_BACKTRACE
#cmakedefine HAVE_BACKTRACE ${HAVE_BACKTRACE}
#endif

/* Define to 1 if you have the `chdir' function. */
#ifndef HAVE_CHDIR
#cmakedefine HAVE_CHDIR ${HAVE_CHDIR}
#endif

/* Define to 1 if you have the `clock' function. */
#ifndef HAVE_CLOCK
#cmakedefine HAVE_CLOCK ${HAVE_CLOCK}
#endif

/* Define to 1 if you have the `clock_gettime' function. */
#ifndef HAVE_CLOCK_GETTIME
#cmakedefine HAVE_CLOCK_GETTIME ${HAVE_CLOCK_GETTIME}
#endif

/* Define to 1 if you have the <crtdbg.h> header file. */
#ifndef HAVE_CRTDBG_H
#cmakedefine HAVE_CRTDBG_H ${HAVE_CRTDBG_H}
#endif

/* Define to 1 if you have the <crt_externs.h> header file. */
#ifndef HAVE_CRT_EXTERNS_H
#cmakedefine HAVE_CRT_EXTERNS_H ${HAVE_CRT_EXTERNS_H}
#endif

/* Define to 1 if you have the `ctime' function. */
#ifndef HAVE_CTIME
#cmakedefine HAVE_CTIME ${HAVE_CTIME}
#endif

/* Define to 1 if you have the <ctype.h> header file. */
#ifndef HAVE_CTYPE_H
#cmakedefine HAVE_CTYPE_H ${HAVE_CTYPE_H}
#endif

/* Define to 1 if you have the `ftime' function. */
#ifndef HAVE_FTIME
#cmakedefine HAVE_FTIME ${HAVE_FTIME}
#endif

/* Define to 1 if you have the <sys/timeb.h> header file. */
#ifndef HAVE_SYS_TIMEB_H
#cmakedefine HAVE_SYS_TIMEB_H ${HAVE_SYS_TIMEB_H}
#endif

/* Define to 1 if you have the <direct.h> header file. */
#ifndef HAVE_DIRECT_H
#cmakedefine HAVE_DIRECT_H ${HAVE_DIRECT_H}
#endif

/* Define to 1 if you have the <dirent.h> header file. */
#ifndef HAVE_DIRENT_H
#cmakedefine HAVE_DIRENT_H ${HAVE_DIRENT_H}
#endif

/* Define to 1 if you have the <dlfcn.h> header file. */
#ifndef HAVE_DLFCN_H
#cmakedefine HAVE_DLFCN_H ${HAVE_DLFCN_H}
#endif

/* Define to 1 if you have the `dlopen' function. */
#ifndef HAVE_DLOPEN
#define HAVE_DLOPEN ${HAVE_DLOPEN}
#endif

/* Define to 1 if you have the `dup2' function. */
#ifndef HAVE_DUP2
#cmakedefine HAVE_DUP2 ${HAVE_DUP2}
#endif

/* Define if dynamic arrays are supported */
#ifndef HAVE_DYNARRAY
#cmakedefine HAVE_DYNARRAY ${HAVE_DYNARRAY}
#endif

/* environment access */
#ifndef HAVE_ENVIRON
#cmakedefine HAVE_ENVIRON ${HAVE_ENVIRON}
#endif

/* Define to 1 if you have the `erf' function. */
#ifndef HAVE_ERF
#cmakedefine HAVE_ERF ${HAVE_ERF}
#endif

/* Define to 1 if you have the <errno.h> header file. */
#ifndef HAVE_ERRNO_H
#cmakedefine HAVE_ERRNO_H ${HAVE_ERRNO_H}
#endif

/* Define to 1 if you have the <execinfo.h> header file. */
#ifndef HAVE_EXECINFO_H
#cmakedefine HAVE_EXECINFO_H ${HAVE_EXECINFO_H}
#endif

/* Define to 1 if you have the <fcntl.h> header file. */
#ifndef HAVE_FCNTL_H
#cmakedefine HAVE_FCNTL_H ${HAVE_FCNTL_H}
#endif

/* Define to 1 if you have the `feclearexcept' function. */
#ifndef HAVE_FECLEAREXCEPT
#cmakedefine HAVE_FECLEAREXCEPT ${HAVE_FECLEAREXCEPT}
#endif

/* Define to 1 if you have the `feenableexcept' function. */
#ifndef HAVE_FEENABLEEXCEPT
#cmakedefine HAVE_FEENABLEEXCEPT ${HAVE_FEENABLEEXCEPT}
#endif

/* Define to 1 if you have the <fenv.h> header file. */
#ifndef HAVE_FENV_H
#cmakedefine HAVE_FENV_H ${HAVE_FENV_H}
#endif

/* Define to 1 if you have the `fesetexceptflag' function. */
#ifndef HAVE_FESETEXCEPTFLAG
#cmakedefine HAVE_FESETEXCEPTFLAG ${HAVE_FESETEXCEPTFLAG}
#endif

/* Define to 1 if you have the `fesetround' function. */
#ifndef HAVE_FESETROUND
#cmakedefine HAVE_FESETROUND ${HAVE_FESETROUND}
#endif

/* Define to 1 if you have the `fesettrapenable' function. */
#ifndef HAVE_FESETTRAPENABLE
#cmakedefine HAVE_FESETTRAPENABLE ${HAVE_FESETTRAPENABLE}
#endif

/* Define to 1 if you have the `fetestexcept' function. */
#ifndef HAVE_FETESTEXCEPT
#cmakedefine HAVE_FETESTEXCEPT ${HAVE_FETESTEXCEPT}
#endif

/* Define to 1 if you have the `ffsl' function. */
#ifndef HAVE_FFSL
#cmakedefine HAVE_FFSL ${HAVE_FFSL}
#endif

/* Define to 1 if you have the `ftell' function. */
    #ifndef HAVE_FTELL
    #cmakedefine HAVE_FTELL ${HAVE_FTELL}
    #endif

/* Define to 1 if you have the `ftello' function. */
#ifndef HAVE_FTELLO
#cmakedefine HAVE_FTELLO ${HAVE_FTELLO}
#endif

/* Define to 1 if you have the `fgetpos' function. */
#ifndef HAVE_FGETPOS
#cmakedefine HAVE_FGETPOS ${HAVE_FGETPOS}
#endif

/* Define to 1 if you have the `finite' function. */
#ifndef HAVE_FINITE
#cmakedefine HAVE_FINITE ${HAVE_FINITE}
#endif

/* Define to 1 if you have the <float.h> header file. */
#ifndef HAVE_FLOAT_H
#cmakedefine HAVE_FLOAT_H ${HAVE_FLOAT_H}
#endif

/* Define to 1 if you have the `flsl' function. */
#ifndef HAVE_FLSL
#cmakedefine HAVE_FLSL ${HAVE_FLSL}
#endif

/* Define to 1 if you have the `flsll' function. */
#ifndef HAVE_FLSLL
#cmakedefine HAVE_FLSLL ${HAVE_FLSLL}
#endif

/* Define to 1 if you have the `fmemopen' function. */
#ifndef HAVE_FMEMOPEN
#cmakedefine HAVE_FMEMOPEN ${HAVE_FMEMOPEN}
#endif
#if CONDA_BUILD
#undef HAVE_FMEMOPEN
#endif

/* Define to 1 if you have the `fpclass' function. */
#ifndef HAVE_FPCLASS
#cmakedefine HAVE_FPCLASS ${HAVE_FPCLASS}
#endif

/* Define to 1 if you have the `fpurge' function. */
#ifndef HAVE_FPURGE
#cmakedefine HAVE_FPURGE ${HAVE_FPURGE}
#endif

/* Define to 1 if you have the <fpu_control.h> header file. */
#ifndef HAVE_FPU_CONTROL_H
#cmakedefine HAVE_FPU_CONTROL_H ${HAVE_FPU_CONTROL_H}
#endif

/* Define to 1 if you have the `ftime' function. */
#ifndef HAVE_FTIME
#cmakedefine HAVE_FTIME ${HAVE_FTIME}
#endif

/* Define to 1 if you have the `ftruncate' function. */
#ifndef HAVE_FTRUNCATE
#cmakedefine HAVE_FTRUNCATE ${HAVE_FTRUNCATE}
#endif

/* Define to 1 if you have the `funopen' function. */
#ifndef HAVE_FUNOPEN
#cmakedefine HAVE_FUNOPEN ${HAVE_FUNOPEN}
#endif

/* Old m4 auto-heder generation, not really useful now */
#ifndef HAVE_GCC
#cmakedefine HAVE_GCC ${HAVE_GCC}
#endif

/* Define to 1 if you have the `getcwd' function. */
#ifndef HAVE_GETCWD
#cmakedefine HAVE_GETCWD ${HAVE_GETCWD}
#endif

/* Define to 1 if you have the `getenv' function. */
#ifndef HAVE_GETENV
#cmakedefine HAVE_GETENV ${HAVE_GETENV}
#endif

/* Define to 1 if you have the `getexecname' function. */
#ifndef HAVE_GETEXECNAME
#cmakedefine HAVE_GETEXECNAME ${HAVE_GETEXECNAME}
#endif

/* Define to 1 if you have the `gethostbyname' function. */
#ifndef HAVE_GETHOSTBYNAME
#cmakedefine HAVE_GETHOSTBYNAME ${HAVE_GETHOSTBYNAME}
#endif

/* Define to 1 if you have the `gethostent' function. */
#ifndef HAVE_GETHOSTENT
#cmakedefine HAVE_GETHOSTENT ${HAVE_GETHOSTENT}
#endif

/* Define to 1 if you have the `gethostid' function. */
#ifndef HAVE_GETHOSTID
#cmakedefine HAVE_GETHOSTID ${HAVE_GETHOSTID}
#endif

/* Define to 1 if you have the `gethostname' function. */
#ifndef HAVE_GETHOSTNAME
#cmakedefine HAVE_GETHOSTNAME ${HAVE_GETHOSTNAME}
#endif

/* Define to 1 if you have the `gethrtime' function. */
#ifndef HAVE_GETHRTIME
#cmakedefine HAVE_GETHRTIME ${HAVE_GETHRTIME}
#endif

/* Define to 1 if you have the `getpagesize' function. */
#ifndef HAVE_GETPAGESIZE
#cmakedefine HAVE_GETPAGESIZE ${HAVE_GETPAGESIZE}
#endif

/* Define to 1 if you have the `getpid' function. */
#ifndef HAVE_GETPID
#cmakedefine HAVE_GETPID ${HAVE_GETPID}
#endif

/* Define to 1 if you have the `getpwnam' function. */
#ifndef HAVE_GETPWNAM
#cmakedefine HAVE_GETPWNAM ${HAVE_GETPWNAM}
#endif

/* Define to 1 if you have the `getrlimit' function. */
#ifndef HAVE_GETRLIMIT
#cmakedefine HAVE_GETRLIMIT ${HAVE_GETRLIMIT}
#endif

/* Define to 1 if you have the `getrusage' function. */
#ifndef HAVE_GETRUSAGE
#cmakedefine HAVE_GETRUSAGE ${HAVE_GETRUSAGE}
#endif

/* Define to 1 if you have the `gettimeofday' function. */
#ifndef HAVE_GETTIMEOFDAY
#cmakedefine HAVE_GETTIMEOFDAY ${HAVE_GETTIMEOFDAY}
#endif

/* Define to 1 if you have the `getwd' function. */
#ifndef HAVE_GETWD
#cmakedefine HAVE_GETWD ${HAVE_GETWD}
#endif

/* Define to 1 if you have the <gmp.h> header file. */
#ifndef HAVE_GMP_H
#cmakedefine HAVE_GMP_H ${HAVE_GMP_H}
#endif

/* Define to 1 if you have the <winsock.h> header file. */
#ifndef HAVE_GLOB_H
#cmakedefine HAVE_GLOB_H ${HAVE_GLOB_H}
#endif

/* Define to 1 if you have the <winsock.h> header file. */
#ifndef HAVE_GLOB
#cmakedefine HAVE_GLOB ${HAVE_GLOB}
#endif

/* Define to 1 if you have the `gmtime' function. */
#ifndef HAVE_GMTIME
#cmakedefine HAVE_GMTIME ${HAVE_GMTIME}
#endif

/* Define of h_errno is provided */
#ifndef HAVE_H_ERRNO
#cmakedefine HAVE_H_ERRNO ${HAVE_H_ERRNO}
#endif

/* Define to 1 if you have the <ieeefp.h> header file. */
#ifndef HAVE_IEEEFP_H
#cmakedefine HAVE_IEEEFP_H ${HAVE_IEEEFP_H}
#endif

/* Define to 1 if you have the <inttypes.h> header file. */
#ifndef HAVE_INTTYPES_H
#cmakedefine HAVE_INTTYPES_H ${HAVE_INTTYPES_H}
#endif

/* Define to 1 if you have the <io.h> header file. */
#ifndef HAVE_IO_H
#cmakedefine HAVE_IO_H ${HAVE_IO_H}
#endif

/* Define to 1 if you have the `isatty' function. */
#ifndef HAVE_ISATTY
#cmakedefine HAVE_ISATTY ${HAVE_ISATTY}
#endif

/* Define to 1 if you have the `isfinite' function. */
#ifndef HAVE_ISFINITE
#cmakedefine HAVE_ISFINITE ${HAVE_ISFINITE}
#endif

/* Define to 1 if you have the `isinf' function. */
#ifndef HAVE_ISINF
#cmakedefine HAVE_ISINF ${HAVE_ISINF}
#endif

/* Define to 1 if you have the `isnan' function. */
#ifndef HAVE_ISNAN
#cmakedefine HAVE_ISNAN ${HAVE_ISNAN}
#endif

/* Define to 1 if you have the `isnan' function. */
#ifndef HAVE_ISWBLANK
#cmakedefine HAVE_ISWBLANK ${HAVE_ISWBLANK}
#endif

/* Define to 1 if you have the `iswspace' function. */
#ifndef HAVE_ISWSPACE
#cmakedefine HAVE_ISWSPACE ${HAVE_ISWSPACE}
#endif

/* Define to 1 if you have the <Judy.h> header file. */
#ifndef HAVE_JUDY_H
#cmakedefine HAVE_JUDY_H ${HAVE_JUDY_H}
#endif

/* Define to 1 if you have the `kill' function. */
#ifndef HAVE_KILL
#cmakedefine HAVE_KILL ${HAVE_KILL}
#endif

/* Define to 1 if you have the `labs' function. */
#ifndef HAVE_LABS
#cmakedefine HAVE_LABS ${HAVE_LABS}
#endif

/* Define to 1 if you have the `lgamma' function. */
#ifndef HAVE_LGAMMA
#cmakedefine HAVE_LGAMMA ${HAVE_LGAMMA}
#endif

/* Define to 1 if you have the `android' library (-landroid). */
#ifndef HAVE_LIBANDROID
#define HAVE_LIBANDROID ${HAVE_LIBANDROID}
#endif

/* Define to 1 if you have the `comdlg32' library (-lcomdlg32). */
#ifndef HAVE_LIBCOMDLG32
#define HAVE_LIBCOMDLG32 ${HAVE_LIBCOMDLG32}
#endif

/* Define to 1 if you have the `crypt' library (-lcrypt). */
#ifndef HAVE_LIBCRYPT
#define HAVE_LIBCRYPT ${HAVE_LIBCRYPT}
#endif

/* Define to 1 if you have the `basename' function. */
#ifndef HAVE_CRYPT
#cmakedefine HAVE_CRYPT ${HAVE_CRYPT}
#endif

/* Define to 1 if you have the <memory.h> header file. */
#ifndef HAVE_LIBGEN_H
#cmakedefine HAVE_LIBGEN_H ${HAVE_LIBGEN_H}
#endif


/* Define to 1 if you have the `gmp' library (-lgmp). */
#ifndef HAVE_LIBGMP
#define HAVE_LIBGMP ${HAVE_LIBGMP}
#endif

/* Define to 1 if you have the `Judy' library (-lJudy). */
#ifndef HAVE_LIBJUDY
#define HAVE_LIBJUDY ${HAVE_LIBJUDY}
#endif

/* Define to 1 if you have the <LibLoaderAPI.h> header file. */
#ifndef HAVE_LIBLOADERAPI_H
#define HAVE_LIBLOADERAPI_H ${HAVE_LIBLOADERAPI_H}
#endif

/* Define to 1 if you have the `log' library (-llog). */
#ifndef HAVE_LIBLOG
#define HAVE_LIBLOG ${HAVE_LIBLOG}
#endif

/* Define to 1 if you have the `m' library (-lm). */
#ifndef HAVE_LIBM
#define HAVE_LIBM ${HAVE_LIBM}
#endif

/* MPI Debugging off */
#ifndef HAVE_LIBMPE
#define HAVE_LIBMPE ${HAVE_LIBMPE}
#endif

/* Define to 1 if you have the `mscrt' library (-lmscrt). */
#ifndef HAVE_LIBMSCRT
#define HAVE_LIBMSCRT ${HAVE_LIBMSCRT}
#endif

/* "Define if you have the nsl library (-lnsl)." */
#ifndef HAVE_LIBNSL
#define HAVE_LIBNSL ${HAVE_LIBNSL}
#endif

/* Define to 1 if you have the `nss_dns' library (-lnss_dns). */
#ifndef HAVE_LIBNSS_DNS
#define HAVE_LIBNSS_DNS ${HAVE_LIBNSS_DNS}
#endif

/* Define to 1 if you have the `nss_files' library (-lnss_files). */
#ifndef HAVE_LIBNSS_FILES
#define HAVE_LIBNSS_FILES ${HAVE_LIBNSS_FILES}
#endif

/* Define to 1 if you have the `psapi' library (-lpsapi). */
#ifndef HAVE_LIBPSAPI
#define HAVE_LIBPSAPI ${HAVE_LIBPSAPI}
#endif

#ifndef HAVE_CRYPT
#cmakedefine HAVE_CRYPT ${HAVE_CRYPT}
#endif


/* Define to 1 if you have the `gmp' library (-lgmp). */
#ifndef HAVE_LIBGMP
#define HAVE_LIBGMP ${HAVE_LIBGMP}
#endif

/* Define to 1 if you have the `Judy' library (-lJudy). */
#ifndef HAVE_LIBJUDY
#define HAVE_LIBJUDY ${HAVE_LIBJUDY}
#endif

/* Define to 1 if you have the <LibLoaderAPI.h> header file. */
#ifndef HAVE_LIBLOADERAPI_H
#define HAVE_LIBLOADERAPI_H ${HAVE_LIBLOADERAPI_H}
#endif

/* Define to 1 if you have the `log' library (-llog). */
#ifndef HAVE_LIBLOG
#define HAVE_LIBLOG ${HAVE_LIBLOG}
#endif

/* Define to 1 if you have the `m' library (-lm). */
#ifndef HAVE_LIBM
#define HAVE_LIBM ${HAVE_LIBM}
#endif

/* MPI Debugging off */
#ifndef HAVE_LIBMPE
#define HAVE_LIBMPE ${HAVE_LIBMPE}
#endif

/* Define to 1 if you have the `mscrt' library (-lmscrt). */
#ifndef HAVE_LIBMSCRT
#define HAVE_LIBMSCRT ${HAVE_LIBMSCRT}
#endif

/* "Define if you have the nsl library (-lnsl)." */
#ifndef HAVE_LIBNSL
#define HAVE_LIBNSL ${HAVE_LIBNSL}
#endif

/* Define to 1 if you have the `nss_dns' library (-lnss_dns). */
#ifndef HAVE_LIBNSS_DNS
#define HAVE_LIBNSS_DNS ${HAVE_LIBNSS_DNS}
#endif

/* Define to 1 if you have the `nss_files' library (-lnss_files). */
#ifndef HAVE_LIBNSS_FILES
#define HAVE_LIBNSS_FILES ${HAVE_LIBNSS_FILES}
#endif

/* Define to 1 if you have the `shlwapi' library (-lshlwapi). */
#ifndef HAVE_LIBSHLWAPI
#define HAVE_LIBSHLWAPI ${HAVE_LIBSHLWAPI}
#endif

/* Define to 1 if you have the `pthread' library (-lpthread). */
#ifndef HAVE_LIBPTHREAD
#define HAVE_LIBPTHREAD ${HAVE_LIBPTHREAD}
#endif

/* Define to 1 if you have the `raptor' library (-lraptor). */
#ifndef HAVE_LIBRAPTOR
#define HAVE_LIBRAPTOR ${HAVE_LIBRAPTOR}
#endif

/* Define to 1 if you have the `raptor2' library (-lraptor2). */
#ifndef HAVE_LIBRAPTOR2
#define HAVE_LIBRAPTOR2 ${HAVE_LIBRAPTOR2}
#endif


/* Define to 1 if you have the `resolv' library (-lresolv). */
#ifndef HAVE_LIBRESOLV
#define HAVE_LIBRESOLV ${HAVE_LIBRESOLV}
#endif

/* Define to 1 if you have the `shell32' library (-lshell32). */
#ifndef HAVE_LIBSHELL32
#define HAVE_LIBSHELL32 ${HAVE_LIBSHELL32}
#endif

/* "Define if you have the socket library (-lsocket)." */
#ifndef HAVE_LIBSOCKET
#define HAVE_LIBSOCKET ${HAVE_LIBSOCKET}
#endif

/* Define to 1 if you have the `stdc++' library (-lstdc++). */
#ifndef HAVE_LIBSTDC__
#define HAVE_LIBSTDC__ ${HAVE_LIBSTDC__}
#endif

/* Whether we have libunicode.a */
#ifndef HAVE_LIBUNICODE
#define HAVE_LIBUNICODE ${HAVE_LIBUNICODE}
#endif

/* Define to 1 if you have the `ws2_32' library (-lws2_32). */
#ifndef HAVE_LIBWS2_32
#define HAVE_LIBWS2_32 ${HAVE_LIBWS2_32}
#endif

/* Define to 1 if you have the `wsock32' library (-lwsock32). */
#ifndef HAVE_LIBWSOCK32
#define HAVE_LIBWSOCK32 ${HAVE_LIBWSOCK32}
#endif

/* Define to 1 if you have the `xnet' library (-lxnet). */
#ifndef HAVE_LIBXNET
#define HAVE_LIBXNET ${HAVE_LIBXNET}
#endif

/* Define to 1 if you have the <limits.h> header file. */
#ifndef HAVE_LIMITS_H
#cmakedefine HAVE_LIMITS_H ${HAVE_LIMITS_H}
#endif

/* Define to 1 if you have the `link' function. */
#ifndef HAVE_LINK
#cmakedefine HAVE_LINK ${HAVE_LINK}
#endif

/* Define to 1 if you have the `LoadLibrary' function. */
#ifndef HAVE_LOADLIBRARY
#cmakedefine HAVE_LOADLIBRARY ${HAVE_LOADLIBRARY}
#endif

/* Define to 1 if you have the `localeconv' function. */
#ifndef HAVE_LOCALECONV
#cmakedefine HAVE_LOCALECONV ${HAVE_LOCALECONV}
#endif

/* Define to 1 if you have the <locale.h> header file. */
#ifndef HAVE_LOCALE_H
#cmakedefine HAVE_LOCALE_H ${HAVE_LOCALE_H}
#endif

/* Define to 1 if you have the `localtime' function. */
#ifndef HAVE_LOCALTIME
#cmakedefine HAVE_LOCALTIME ${HAVE_LOCALTIME}
#endif

/* Define to 1 if the system has the type `long long'. */
#ifndef HAVE_LONG_LONG
#cmakedefine HAVE_LONG_LONG ${HAVE_LONG_LONG}
#endif

/* Define to 1 if you have the `lstat' function. */
#ifndef HAVE_LSTAT
#cmakedefine HAVE_LSTAT ${HAVE_LSTAT}
#endif

/* Define to 1 if you have the <mach-o/dyld.h> header file. */
#ifndef HAVE_MACH_O_DYLD_H
#cmakedefine HAVE_MACH_O_DYLD_H ${HAVE_MACH_O_DYLD_H}
#endif

/* Define to 1 if you have the `mallinfo' function. */
#ifndef HAVE_MALLINFO
#cmakedefine HAVE_MALLINFO ${HAVE_MALLINFO}
#endif

/* Define to 1 if you have the <malloc.h> header file. */
#ifndef HAVE_MALLOC_H
#cmakedefine HAVE_MALLOC_H ${HAVE_MALLOC_H}
#endif

/* Define to 1 if you have the <math.h> header file. */
#ifndef HAVE_MATH_H
#cmakedefine HAVE_MATH_H ${HAVE_MATH_H}
#endif

/* Define to 1 if you have the `mbscasecoll' function. */
#ifndef HAVE_MBSCASECOLL
#cmakedefine HAVE_MBSCASECOLL ${HAVE_MBSCASECOLL}
#endif

/* Define to 1 if you have the `mbscoll' function. */
#ifndef HAVE_MBSCOLL
#cmakedefine HAVE_MBSCOLL ${HAVE_MBSCOLL}
#endif

/* Define to 1 if you have the `mbsnrtowcs' function. */
#ifndef HAVE_MBSNRTOWCS
#cmakedefine HAVE_MBSNRTOWCS ${HAVE_MBSNRTOWCS}
#endif

/* Define to 1 if you have the `memmove' function. */
#ifndef HAVE_MEMCPY
#cmakedefine HAVE_MEMCPY ${HAVE_MEMCPY}
#endif

/* Define to 1 if you have the `memmove' function. */
#ifndef HAVE_MEMMOVE
#cmakedefine HAVE_MEMMOVE ${HAVE_MEMMOVE}
#endif

/* Define to 1 if you have the <memory.h> header file. */
#ifndef HAVE_MEMORY_H
#cmakedefine HAVE_MEMORY_H ${HAVE_MEMORY_H}
#endif

/* Define to 1 if you have the `mkstemp' function. */
#ifndef HAVE_MKSTEMP
#cmakedefine HAVE_MKSTEMP ${HAVE_MKSTEMP}
#endif

/* Define to 1 if you have the `mktemp' function. */
#ifndef HAVE_MKTEMP
#cmakedefine HAVE_MKTEMP ${HAVE_MKTEMP}
#endif

/* Define to 1 if you have the `mktime' function. */
#ifndef HAVE_MKTIME
#cmakedefine HAVE_MKTIME ${HAVE_MKTIME}
#endif

/* Define to 1 if you have the `mmap' function. */
#ifndef HAVE_MMAP
#cmakedefine HAVE_MMAP ${HAVE_MMAP}
#endif

/* Define to 1 if you have the <mpe.h> header file. */
#ifndef HAVE_MPE_H
#cmakedefine HAVE_MPE_H ${HAVE_MPE_H}
#endif

/* Define to 1 if you have the <mpi.h> header file. */
#ifndef HAVE_MPI_H
#cmakedefine HAVE_MPI_H ${HAVE_MPI_H}
#endif

/* Define to 1 if you have the <mtrace> glibc extension. */
#ifndef HAVE_MPI_H
#cmakedefine HAVE_MTRACE ${HAVE_TRACE}
#endif

/* Older versions of MPZ didn't have XOR */
#ifndef HAVE_MPZ_XOR
#cmakedefine HAVE_MPZ_XOR ${HAVE_MPZ_XOR}
#endif

/* Define to 1 if you have the <mysql/mysql.h> header file. */
#ifndef HAVE_MYSQL_MYSQL_H
#cmakedefine HAVE_MYSQL_MYSQL_H ${HAVE_MYSQL_MYSQL_H}
#endif

/* Define to 1 if you have the `nanosleep' function. */
#ifndef HAVE_NANOSLEEP
#cmakedefine HAVE_NANOSLEEP ${HAVE_NANOSLEEP}
#endif

/* Define to 1 if you have the <netdb.h> header file. */
#ifndef HAVE_NETDB_H
#cmakedefine HAVE_NETDB_H ${HAVE_NETDB_H}
#endif

/* Define to 1 if you have the <netinet/in.h> header file. */
#ifndef HAVE_NETINET_IN_H
#cmakedefine HAVE_NETINET_IN_H ${HAVE_NETINET_IN_H}
#endif

/* Define to 1 if you have the <netinet/tcp.h> header file. */
#ifndef HAVE_NETINET_TCP_H
#cmakedefine HAVE_NETINET_TCP_H ${HAVE_NETINET_TCP_H}
#endif

/* Define to 1 if you have the `NSLinkModule' function. */
#ifndef HAVE_NSLINKMODULE
#cmakedefine HAVE_NSLINKMODULE ${HAVE_NSLINKMODULE}
#endif

/* c++ nullptr support */
#ifndef HAVE_NULLPTR
#cmakedefine HAVE_NULLPTR ${HAVE_NULLPTR}
#endif

/* Define to 1 if you have the `open_memstream' function. */
#ifndef HAVE_OPEN_MEMSTREAM
#cmakedefine HAVE_OPEN_MEMSTREAM ${HAVE_OPEN_MEMSTREAM}
#endif
#if CONDA_BUILD
#undef HAVE_OPEN_MEMSTREAM
#endif


/* Define to 1 if you have the `opendir' function. */
#ifndef HAVE_OPENDIR
#cmakedefine HAVE_OPENDIR ${HAVE_OPENDIR}
#endif

/* Define to 1 if you have the `pipe2' function. */
#ifndef HAVE_PIPE2
#cmakedefine HAVE_PIPE2 ${HAVE_PIPE2}
#endif

/* Define to 1 if you have the `popen' function. */
#ifndef HAVE_POPEN
#cmakedefine HAVE_POPEN ${HAVE_POPEN}
#endif

/* Define to 1 if you have the <pthread.h> header file. */
#ifndef HAVE_PTHREAD_H
#cmakedefine HAVE_PTHREAD_H ${HAVE_PTHREAD_H}
#endif

/* Define to 1 if you have the `pthread_mutexattr_setkind_np' function. */
#ifndef HAVE_PTHREAD_MUTEXATTR_SETKIND_NP
#cmakedefine HAVE_PTHREAD_MUTEXATTR_SETKIND_NP ${HAVE_PTHREAD_MUTEXATTR_SETKIND_NP}
#endif

/* Define to 1 if you have the `pthread_mutexattr_settype' function. */
#ifndef HAVE_PTHREAD_MUTEXATTR_SETTYPE
#cmakedefine HAVE_PTHREAD_MUTEXATTR_SETTYPE ${HAVE_PTHREAD_MUTEXATTR_SETTYPE}
#endif

/* Define to 1 if you have the `pthread_setconcurrency' function. */
#ifndef HAVE_PTHREAD_SETCONCURRENCY
#cmakedefine HAVE_PTHREAD_SETCONCURRENCY ${HAVE_PTHREAD_SETCONCURRENCY}
#endif

/* Define to 1 if you have the `putenv' function. */
#ifndef HAVE_PUTENV
#cmakedefine HAVE_PUTENV ${HAVE_PUTENV}
#endif

/* Define to 1 if you have the <pwd.h> header file. */
#ifndef HAVE_PWD_H
#cmakedefine HAVE_PWD_H ${HAVE_PWD_H}
#endif

/* Define to 1 if you have the <pwd.h> header file. */
#ifndef HAVE_PYTHON_H
#cmakedefine HAVE_PYTHON_H ${HAVE_PYTHON_H}
#endif

/* Define to 1 if you have the `rand' function. */
#ifndef HAVE_RAND
#cmakedefine HAVE_RAND ${HAVE_RAND}
#endif

/* Define to 1 if you have the `random' function. */
#ifndef HAVE_RANDOM
#cmakedefine HAVE_RANDOM ${HAVE_RANDOM}
#endif

/* Define to 1 if you have the <raptor2/raptor2.h> header file. */
#ifndef HAVE_RAPTOR2_RAPTOR2_H
#cmakedefine HAVE_RAPTOR2_RAPTOR2_H ${HAVE_RAPTOR2_RAPTOR2_H}
#endif

/* Define to 1 if you have the <raptor.h> header file. */
#ifndef HAVE_RAPTOR_H
#cmakedefine HAVE_RAPTOR_H ${HAVE_RAPTOR_H}
#endif

/* Define to 1 if you have the `readlink' function. */
#ifndef HAVE_READLINK
#cmakedefine HAVE_READLINK ${HAVE_READLINK}
#endif

/* Define to 1 if you have the `realpath' function. */
#ifndef HAVE_REALPATH
#cmakedefine HAVE_REALPATH ${HAVE_REALPATH}
#endif

/* Define to 1 if you have the `regexec' function. */
#ifndef HAVE_REGEXEC
#cmakedefine HAVE_REGEXEC ${HAVE_REGEXEC}
#endif

/* Define to 1 if you have the <regex.h> header file. */
#ifndef HAVE_REGEX_H
#cmakedefine HAVE_REGEX_H ${HAVE_REGEX_H}
#endif

/* Define to 1 if you have the <Rembedded.h> header file. */
#ifndef HAVE_REMBEDDED_H
#cmakedefine HAVE_REMBEDDED_H ${HAVE_REMBEDDED_H}
#endif

/* Define to 1 if you have the `rename' function. */
#ifndef HAVE_RENAME
#cmakedefine HAVE_RENAME ${HAVE_RENAME}
#endif

/* Define to 1 if system calls automatically restart after interruption by a
signal. */
#ifndef HAVE_RESTARTABLE_SYSCALLS
#cmakedefine HAVE_RESTARTABLE_SYSCALLS ${HAVE_RESTARTABLE_SYSCALLS}
#endif

/* Define to 1 if you have the `rint' function. */
#ifndef HAVE_RINT
#cmakedefine HAVE_RINT ${HAVE_RINT}
#endif

/* Define to 1 if you have the <Rinterface.h> header file. */
#ifndef HAVE_RINTERFACE_H
#cmakedefine HAVE_RINTERFACE_H ${HAVE_RINTERFACE_H}
#endif

/* Define to 1 if you have the <R.h> header file. */
#ifndef HAVE_R_H
#cmakedefine HAVE_R_H ${HAVE_R_H}
#endif

/* Define to 1 if you have the `sbrk' function. */
#ifndef HAVE_SBRK
#cmakedefine HAVE_SBRK ${HAVE_SBRK}
#endif

/* Define to 1 if you have the `select' function. */
#ifndef HAVE_SELECT
#cmakedefine HAVE_SELECT ${HAVE_SELECT}
#endif

/* Define to 1 if you have the `setbuf' function. */
#ifndef HAVE_SETBUF
#cmakedefine HAVE_SETBUF ${HAVE_SETBUF}
#endif

/* Define to 1 if you have the `setitimer' function. */
#ifndef HAVE_SETITIMER
#cmakedefine HAVE_SETITIMER ${HAVE_SETITIMER}
#endif

/* Define to 1 if you have the `setlinebuf' function. */
#ifndef HAVE_SETLINEBUF
#cmakedefine HAVE_SETLINEBUF ${HAVE_SETLINEBUF}
#endif

/* Define to 1 if you have the `setlocale' function. */
#ifndef HAVE_SETLOCALE
#cmakedefine HAVE_SETLOCALE ${HAVE_SETLOCALE}
#endif

/* Define to 1 if you have the `setsid' function. */
#ifndef HAVE_SETSID
#cmakedefine HAVE_SETSID ${HAVE_SETSID}
#endif

/* Define to 1 if you have the <shlobj.h> header file. */
#ifndef HAVE_SHLOBJ_H
#cmakedefine HAVE_SHLOBJ_H ${HAVE_SHLOBJ_H}
#endif

/* Define to 1 if you have the `shmat' function. */
#ifndef HAVE_SHMAT
#cmakedefine HAVE_SHMAT ${HAVE_SHMAT}
#endif

/* Define to 1 if you have the `sigaction' function. */
#ifndef HAVE_SIGACTION
#cmakedefine HAVE_SIGACTION ${HAVE_SIGACTION}
#endif

/* Unix SIGFPE */
#ifndef HAVE_SIGFPE
#cmakedefine HAVE_SIGFPE ${HAVE_SIGFPE}
#endif

/* Define to 1 if you have the `siggetmask' function. */
#ifndef HAVE_SIGGETMASK
#cmakedefine HAVE_SIGGETMASK ${HAVE_SIGGETMASK}
#endif

/* Unix SIGINFO */
#ifndef HAVE_SIGINFO
#cmakedefine HAVE_SIGINFO ${HAVE_SIGINFO}
#endif

/* Define to 1 if you have the <siginfo.h> header file. */
#ifndef HAVE_SIGINFO_H
#cmakedefine HAVE_SIGINFO_H ${HAVE_SIGINFO_H}
#endif

/* Define to 1 if you have the `siginterrupt' function. */
#ifndef HAVE_SIGINTERRUPT
#cmakedefine HAVE_SIGINTERRUPT ${HAVE_SIGINTERRUPT}
#endif

/* Define to 1 if you have the `signal' function. */
#ifndef HAVE_SIGNAL
#cmakedefine HAVE_SIGNAL ${HAVE_SIGNAL}
#endif

/* Define to 1 if you have the <signal.h> header file. */
#ifndef HAVE_SIGNAL_H
#cmakedefine HAVE_SIGNAL_H ${HAVE_SIGNAL_H}
#endif

/* Define to 1 if you have the `sigprocmask' function. */
#ifndef HAVE_SIGPROCMASK
#cmakedefine HAVE_SIGPROCMASK ${HAVE_SIGPROCMASK}
#endif

/* UNIX Signal SIGPROF */
#ifndef HAVE_SIGPROF
#cmakedefine HAVE_SIGPROF ${HAVE_SIGPROF}
#endif

/* UNIX signal SEGV */
#ifndef HAVE_SIGSEGV
#cmakedefine HAVE_SIGSEGV ${HAVE_SIGSEGV}
#endif

/* support for sigsetjmp */
#ifndef HAVE_SIGSETJMP
#cmakedefine HAVE_SIGSETJMP ${HAVE_SIGSETJMP}
#endif

/* Define to 1 if you have the `sleep' function. */
#ifndef HAVE_SLEEP
#cmakedefine HAVE_SLEEP ${HAVE_SLEEP}
#endif

/* Define to 1 if you have the `snprintf' function. */
#ifndef HAVE_SNPRINTF
#cmakedefine HAVE_SNPRINTF ${HAVE_SNPRINTF}
#endif

/* Define to 1 if you have the `socket' function. */
#ifndef HAVE_SOCKET
#cmakedefine HAVE_SOCKET ${HAVE_SOCKET}
#endif

/* Define to 1 if the system has the type `socklen_t'. */
#ifndef HAVE_SOCKLEN_T
#cmakedefine HAVE_SOCKLEN_T ${HAVE_SOCKLEN_T}
#endif

/* Define to 1 if you have the <sqlite3.h> header file. */
#ifndef HAVE_SQLITE3_H
#cmakedefine HAVE_SQLITE3_H ${HAVE_SQLITE3_H}
#endif

/* Define to 1 if the system has the type `SQLLEN'. */
#ifndef HAVE_SQLLEN
#cmakedefine HAVE_SQLLEN ${HAVE_SQLLEN}
#endif

/* Define to 1 if the system has the type `SQLULEN'. */
#ifndef HAVE_SQLULEN
#cmakedefine HAVE_SQLULEN ${HAVE_SQLULEN}
#endif

/* Define to 1 if you have the <sql.h> header file. */
#ifndef HAVE_SQL_H
#cmakedefine HAVE_SQL_H ${HAVE_SQL_H}
#endif

/* Define to 1 if you have the `srand' function. */
#ifndef HAVE_SRAND
#cmakedefine HAVE_SRAND ${HAVE_SRAND}
#endif

/* Define to 1 if you have the `srandom' function. */
#ifndef HAVE_SRANDOM
#cmakedefine HAVE_SRANDOM ${HAVE_SRANDOM}
#endif

/* Define to 1 if the system has the type `ssize_t'. */
#ifndef HAVE_SSIZE_T
#cmakedefine HAVE_SSIZE_T ${HAVE_SSIZE_T}
#endif

/* Define to 1 if you have the `stat' function. */
#ifndef HAVE_STAT
#cmakedefine HAVE_STAT ${HAVE_STAT}
#endif

/* Define to 1 if you have the <stdarg.h> header file. */
#ifndef HAVE_STDARG_H
#cmakedefine HAVE_STDARG_H ${HAVE_STDARG_H}
#endif

/* Define to 1 if you have the <stdbool.h> header file. */
#ifndef HAVE_STDBOOL_H
#cmakedefine HAVE_STDBOOL_H ${HAVE_STDBOOL_H}
#endif

/* Define to 1 if you have stdc headers. */
#ifndef STDC_HEADERS
#cmakedefine STDC_HEADERS ${STDC_HEADERS}
#endif
#if STDC_HEADERS
#define HAVE_FLOAT_H 1
#define HAVE_STRING_H 1
#define HAVE_STDARG_H 1
#define HAVE_STDLIB_H 1
#endif

/* Define to 1 if you have the <stdint.h> header file. */
#ifndef HAVE_STDINT_H
#cmakedefine HAVE_STDINT_H ${HAVE_STDINT_H}
#endif

/* Define to 1 if you have the <stdlib.h> header file. */
#ifndef HAVE_STDLIB_H
#cmakedefine HAVE_STDLIB_H ${HAVE_STDLIB_H}
#endif

/* Define to 1 if you have the `strcasecmp' function. */
#ifndef HAVE_STRCASECMP
#cmakedefine HAVE_STRCASECMP ${HAVE_STRCASECMP}
#endif

/* Define to 1 if you have the `strcasestr' function. */
#ifndef HAVE_STRCASESTR
#cmakedefine HAVE_STRCASESTR ${HAVE_STRCASESTR}
#endif

/* Define to 1 if you have the `strchr' function. */
#ifndef HAVE_STRCHR
#cmakedefine HAVE_STRCHR ${HAVE_STRCHR}
#endif

/* Define to 1 if you have the `strerror' function. */
#ifndef HAVE_STRERROR
#cmakedefine HAVE_STRERROR ${HAVE_STRERROR}
#endif

/* Define to 1 if you have the `stricmp' function. */
#ifndef HAVE_STRICMP
#cmakedefine HAVE_STRICMP ${HAVE_STRICMP}
#endif

/* Define to 1 if you have the <strings.h> header file. */
#ifndef HAVE_STRINGS_H
#cmakedefine HAVE_STRINGS_H ${HAVE_STRINGS_H}
#endif

/* Define to 1 if you have the <string.h> header file. */
#ifndef HAVE_STRING_H
#cmakedefine HAVE_STRING_H ${HAVE_STRING_H}
#endif

/* Define to 1 if you have the `strlcpy' function. */
#ifndef HAVE_STRLCPY
#cmakedefine HAVE_STRLCPY ${HAVE_STRLCPY}
#endif

/* Define to 1 if you have the `strlwr' function. */
#ifndef HAVE_STRLWR
#cmakedefine HAVE_STRLWR ${HAVE_STRLWR}
#endif

/* Define to 1 if you have the `strncasecmp' function. */
#ifndef HAVE_STRNCASECMP
#cmakedefine HAVE_STRNCASECMP ${HAVE_STRNCASECMP}
#endif

/* Define to 1 if you have the `strncat' function. */
#ifndef HAVE_STRNCAT
#cmakedefine HAVE_STRNCAT ${HAVE_STRNCAT}
#endif

/* Define to 1 if you have the `strncpy' function. */
#ifndef HAVE_STRNCPY
#cmakedefine HAVE_STRNCPY ${HAVE_STRNCPY}
#endif

/* Define to 1 if you have the `strnlen' function. */
#ifndef HAVE_STRNLEN
#cmakedefine HAVE_STRNLEN ${HAVE_STRNLEN}
#endif

/* Define to 1 if you have the `stpcpy' function. */
#ifndef HAVE_STPCPY
#cmakedefine HAVE_STPCPY ${HAVE_STPCPY}
#endif

/* Define to 1 if you have the <stropts.h> header file. */
#ifndef HAVE_STROPTS_H
#cmakedefine HAVE_STROPTS_H ${HAVE_STROPTS_H}
#endif

/* Define to 1 if you have the `strtod' function. */
#ifndef HAVE_STRTOD
#cmakedefine HAVE_STRTOD ${HAVE_STRTOD}
#endif

/* Define to 1 if you have the `tcflush' function. */
#ifndef HAVE_TCFLUSH
#cmakedefine HAVE_TCFLUSH ${HAVE_TCFLUSH}
#endif

/* Define is struct tm has tm_gmtoff */
#ifndef HAVE_STRUCT_TIME_TM_GMTOFF
#cmakedefine HAVE_STRUCT_TIME_TM_GMTOFF ${HAVE_STRUCT_TIME_TM_GMTOFF}
#endif

/* Define to 1 if you have the <syslog.h> header file. */
#ifndef HAVE_SYSLOG_H
#cmakedefine HAVE_SYSLOG_H ${HAVE_SYSLOG_H}
#endif

/* Define to 1 if you have the `system' function. */
#ifndef HAVE_SYSTEM
#cmakedefine HAVE_SYSTEM ${HAVE_SYSTEM}
#endif

/* Define to 1 if you have the <sys/conf.h> header file. */
#ifndef HAVE_SYS_CONF_H
#cmakedefine HAVE_SYS_CONF_H ${HAVE_SYS_CONF_H}
#endif

/* Define to 1 if you have the <sys/dir.h> header file. */
#ifndef HAVE_SYS_DIR_H
#cmakedefine HAVE_SYS_DIR_H ${HAVE_SYS_DIR_H}
#endif

/* Define to 1 if you have the <sys/file.h> header file. */
#ifndef HAVE_SYS_FILE_H
#cmakedefine HAVE_SYS_FILE_H ${HAVE_SYS_FILE_H}
#endif

/* Define to 1 if you have the <sys/mman.h> header file. */
#ifndef HAVE_SYS_MMAN_H
#cmakedefine HAVE_SYS_MMAN_H ${HAVE_SYS_MMAN_H}
#endif

/* Define to 1 if you have the <sys/ndir.h> header file. */
#ifndef HAVE_SYS_NDIR_H
#cmakedefine HAVE_SYS_NDIR_H ${HAVE_SYS_NDIR_H}
#endif

/* Define to 1 if you have the <sys/param.h> header file. */
#ifndef HAVE_SYS_PARAM_H
#cmakedefine HAVE_SYS_PARAM_H ${HAVE_SYS_PARAM_H}
#endif

/* Define to 1 if you have the <sys/resource.h> header file. */
#ifndef HAVE_SYS_RESOURCE_H
#cmakedefine HAVE_SYS_RESOURCE_H ${HAVE_SYS_RESOURCE_H}
#endif

/* Define to 1 if you have the <sys/select.h> header file. */
#ifndef HAVE_SYS_SELECT_H
#cmakedefine HAVE_SYS_SELECT_H ${HAVE_SYS_SELECT_H}
#endif

/* Define to 1 if you have the <sys/shm.h> header file. */
#ifndef HAVE_SYS_SHM_H
#cmakedefine HAVE_SYS_SHM_H ${HAVE_SYS_SHM_H}
#endif

/* Define to 1 if you have the <sys/socket.h> header file. */
#ifndef HAVE_SYS_SOCKET_H


#cmakedefine HAVE_SYS_SOCKET_H ${HAVE_SYS_SOCKET_H}
#endif

/* Define to 1 if you have the <sys/stat.h> header file. */
#ifndef HAVE_SYS_STAT_H
#cmakedefine HAVE_SYS_STAT_H ${HAVE_SYS_STAT_H}
#endif

/* Define to 1 if you have the <sys/syscall.h> header file. */
#ifndef HAVE_SYS_SYSCALL_H
#cmakedefine HAVE_SYS_SYSCALL_H ${HAVE_SYS_SYSCALL_H}
#endif

/* Define to 1 if you have the <termios.h> header file. */
#ifndef HAVE_TERMIOS_H
#cmakedefine HAVE_TERMIOS_H ${HAVE_TERMIOS_H}
#endif

/* Define to 1 if you have the <sys/times.h> header file. */
#ifndef HAVE_SYS_TIMES_H
#cmakedefine HAVE_SYS_TIMES_H ${HAVE_SYS_TIMES_H}
#endif

/* Define to 1 if you have the <sys/time.h> header file. */
#ifndef HAVE_SYS_TIME_H
#cmakedefine HAVE_SYS_TIME_H ${HAVE_SYS_TIME_H}
#endif

/* Define to 1 if you have the <sys/types.h> header file. */
#ifndef HAVE_SYS_TYPES_H
#cmakedefine HAVE_SYS_TYPES_H ${HAVE_SYS_TYPES_H}
#endif

/* Define to 1 if you have the <sys/ucontext.h> header file. */
#ifndef HAVE_SYS_UCONTEXT_H
#cmakedefine HAVE_SYS_UCONTEXT_H ${HAVE_SYS_UCONTEXT_H}
#endif

/* Define to 1 if you have the <sys/un.h> header file. */
#ifndef HAVE_SYS_UN_H
#cmakedefine HAVE_SYS_UN_H ${HAVE_SYS_UN_H}
#endif

/* Define to 1 if you have the <sys/wait.h> header file. */
#ifndef HAVE_SYS_WAIT_H
#cmakedefine HAVE_SYS_WAIT_H ${HAVE_SYS_WAIT_H}
#endif

/* Define to 1 if you have the `time' function. */
#ifndef HAVE_TIME
#cmakedefine HAVE_TIME ${HAVE_TIME}
#endif

/* Define to 1 if you have the `timegm' function. */
#ifndef HAVE_TIMEGM
#cmakedefine HAVE_TIMEGM ${HAVE_TIMEGM}
#endif

/* Define to 1 if you have the `times' function. */
#ifndef HAVE_TIMES
#cmakedefine HAVE_TIMES ${HAVE_TIMES}
#endif

/* Define to 1 if you have the <time.h> header file. */
#ifndef HAVE_TIME_H
#cmakedefine HAVE_TIME_H ${HAVE_TIME_H}
#endif
#if HAVE_TIME_H && HAVE_SYS_TIME_H
#ifndef TIME_WITH_SYS_TIME_H
#define TIME_WITH_SYS_TIME_H 1
#endif
#endif

/* Define to 1 if you have the `tmpnam' function. */
#ifndef HAVE_TMPNAM
#cmakedefine HAVE_TMPNAM ${HAVE_TMPNAM}
#endif

/* Define to 1 if you have the `ttyname' function. */
#ifndef HAVE_TTYNAME
#cmakedefine HAVE_TTYNAME ${HAVE_TTYNAME}
#endif

/* Define to 1 if you have the <ucontext.h> header file. */
#ifndef HAVE_UCONTEXT_H
#cmakedefine HAVE_UCONTEXT_H ${HAVE_UCONTEXT_H}
#endif

/* Define to 1 if you have the <unistd.h> header file. */
#ifndef HAVE_UNISTD_H
#cmakedefine HAVE_UNISTD_H ${HAVE_UNISTD_H}
#endif

/* Define to 1 if you have the `usleep' function. */
#ifndef HAVE_USLEEP
#cmakedefine HAVE_USLEEP ${HAVE_USLEEP}
#endif

/* Define to 1 if you have the `utime' function. */
#ifndef HAVE_UTIME
#cmakedefine HAVE_UTIME ${HAVE_UTIME}
#endif

/* Define to 1 if you have the <utime.h> header file. */
#ifndef HAVE_UTIME_H
#cmakedefine HAVE_UTIME_H ${HAVE_UTIME_H}
#endif

/* Define if tzset sets timezone variable */
#ifndef HAVE_VAR_TIMEZONE
#define HAVE_VAR_TIMEZONE ${HAVE_VAR_TIMEZONE}
#endif

/* Define to 1 if you have the `vfork' function. */
#ifndef HAVE_VFORK
#cmakedefine HAVE_VFORK ${HAVE_VFORK}
#endif

/* Define to 1 if you have the `vsnprintf' function. */
#ifndef HAVE_VSNPRINTF
#cmakedefine HAVE_VSNPRINTF ${HAVE_VSNPRINTF}
#endif

/* Define to 1 if you have the `waitpid' function. */
#ifndef HAVE_WAITPID
#cmakedefine HAVE_WAITPID ${HAVE_WAITPID}
#endif

/* Define to 1 if you have the <wchar.h> header file. */
#ifndef HAVE_WCHAR_H
#cmakedefine HAVE_WCHAR_H ${HAVE_WCHAR_H}
#endif

/* Define to 1 if you have the `wcsdup' function. */
#ifndef HAVE_WCSDUP
#cmakedefine HAVE_WCSDUP ${HAVE_WCSDUP}
#endif

/* Define to 1 if you have the `wcsnlen' function. */
#ifndef HAVE_WCSNLEN
#cmakedefine HAVE_WCSNLEN ${HAVE_WCSNLEN}
#endif

/* Define to 1 if you have the <wctype.h> header file. */
#ifndef HAVE_WCTYPE_H
#cmakedefine HAVE_WCTYPE_H ${HAVE_WCTYPE_H}
#endif

/* Define to 1 if you have the <windef.h> header file. */
#ifndef HAVE_WINDEF_H
#cmakedefine HAVE_WINDEF_H ${HAVE_WINDEF_H}
#endif

/* Define to 1 if you have the <windows.h> header file. */
#ifndef HAVE_WINDOWS_H
#cmakedefine HAVE_WINDOWS_H ${HAVE_WINDOWS_H}
#endif

/* Define to 1 if you have the <winsock2.h> header file. */
#ifndef HAVE_WINSOCK2_H
#cmakedefine HAVE_WINSOCK2_H ${HAVE_WINSOCK2_H}
#endif

/* Define to 1 if you have the <winsock.h> header file. */
#ifndef HAVE_WORDEXP
#cmakedefine HAVE_WORDEXP ${HAVE_WORDEXP}
#endif

/* Define to 1 if you have the <winsock.h> header file. */
#ifndef HAVE_WORDEXP_H
#cmakedefine HAVE_WORDEXP_H ${HAVE_WORDEXP_H}
#endif

/* Define to 1 if you have <zlib.h>. */
#ifndef HAVE_ZLIB_H
#cmakedefine HAVE_ZLIB_H ${HAVE_ZLIB_H}
#endif

/* Define to 1 if you have the <zutil.h> header file. */
#ifndef HAVE_ZUTIL_H
#cmakedefine HAVE_ZUTIL_H ${HAVE_ZUTIL_H}
#endif

/* Define to 1 if the system has the type `_Bool'. */
#ifndef HAVE__BOOL
#cmakedefine HAVE__BOOL ${HAVE__BOOL}
#endif

/* Define to 1 if you have the `_chsize_s' function. */
#ifndef HAVE__CHSIZE_S
#cmakedefine HAVE__CHSIZE_S ${HAVE__CHSIZE_S}
#endif

/* Define to 1 if you have the `_NSGetEnviron' function. */
#ifndef HAVE__NSGETENVIRON
#cmakedefine HAVE__NSGETENVIRON ${HAVE__NSGETENVIRON}
#endif

/* Define to 1 if you have the `__builtin_ffsll' function. */
#ifndef HAVE___BUILTIN_FFSLL
#cmakedefine HAVE___BUILTIN_FFSLL ${HAVE___BUILTIN_FFSLL}
#endif

/* what is the configure host name */
#ifndef HOST_ALIAS
#define HOST_ALIAS "${CMAKE_SYSTEM}"
#endif

/* type of int64_t */
#ifndef INT64_T_DEFINED
#cmakedefine INT64_T_DEFINED "${INT64_T_DEFINED}"
#endif

/* malloc_t */
#ifndef MALLOC_T
#define MALLOC_T void *
#endif

/* max number of threads, default 1 or 1024 */
#ifndef MAX_THREADS
#define MAX_THREADS ${WITH_MAX_Threads}
#endif

/* maximum amount of or-parallelism */
#ifndef MAX_WORKERS
#define MAX_WORKERS ${WITH_MAX_Workers}
#endif

/* o not use realloc() from HP-UX 10.20 together with MPI */
#ifndef MPI_AVOID_REALLOC
#cmakedefine MPI_AVOID_REALLOC "${MPI_AVOID_REALLOC}"
#endif

/* compiler should shift offsets. */
#ifndef MSHIFTOFFS
#cmakedefine MSHIFTOFFS ${MSHIFTOFFS}
#endif

/* myddas release */
#ifndef MYDDAS_VERSION
#define MYDDAS_VERSION "${MYDDAS_VERSION}"
#endif

/* at least 2M Cells for Heap */
#ifndef MinHeapSpace
#define MinHeapSpace ${MIN_HEAPSPACE}
#endif

/* at least 1M Cells for Stack */
#ifndef MinStackSpace
#define MinStackSpace ${MIN_STACKSPACE}
#endif

/* at least 1/2M Cells for Trail */
#ifndef MinTrailSpace
#define MinTrailSpace ${MIN_TRAILSPACE}
#endif

/* at least 2M Cells for Heap */
#ifndef DefHeapSpace
#define DefHeapSpace ${DEF_HEAPSPACE}
#endif

/* at least 1M Cells for Stack */
#ifndef DefStackSpace
#define DefStackSpace ${DEF_STACKSPACE}
#endif

/* at least 1/2M Cells for Trail */
#ifndef DefTrailSpace
#define DefTrailSpace ${DEF_TRAILSPACE}
#endif

/* compile wait in UNIX */
#ifndef NO_UNION_WAIT
#cmakedefine NO_UNION_WAIT "${NO_UNION_WAIT}"
#endif

/* Define to the address where bug reports for this package should be sent. */
#ifndef PACKAGE_BUGREPORT
#cmakedefine PACKAGE_BUGREPORT "${PACKAGE_BUGREPORT}"
#endif

/* Define to the full name of this package. */
#ifndef PACKAGE_NAME
#cmakedefine PACKAGE_NAME "${PACKAGE_NAME}"
#endif

/* Define to the full name and version of this package. */
#ifndef PACKAGE_STRING
#cmakedefine PACKAGE_STRING "${PACKAGE_STRING}"
#endif

/* Define to the one symbol short name of this package. */
#ifndef PACKAGE_TARNAME
#cmakedefine PACKAGE_TARNAME "${PACKAGE_TARNAME}"
#endif

/* Define to the home page for this package. */
#ifndef PACKAGE_URL
#cmakedefine PACKAGE_URL "${PACKAGE_URL}"
#endif

/* Define to the version of this package. */
#ifndef YAP_FULL_VERSION
#define YAP_FULL_VERSION "[ YAP ${YAP_FULL_GIT_VERSION} (${CMAKE_SYSTEM}-${YAP_ARCH}): ${YAP_TIMESTAMP}@${YAP_SITE} ]\n"
#endif

/* Define to the version of this package. */
#ifndef YAP_GIT_HEAD
#define YAP_GIT_HEAD g_GIT_SHA1
#endif

/* Define to the version of this package. */
#ifndef YAP_NUMERIC_VERSION
#define YAP_NUMERIC_VERSION "${YAP_NUMERIC_VERSION}"
#endif

/* Define as the return type of signal handlers (`int' or `void'). */
#ifndef RETSIGTYPE
#cmakedefine RETSIGTYPE ${RETSIGTYPE}
#endif

/* Specify package */
#ifndef RFC2045PKG
#cmakedefine RFC2045PKG "${RFC2045PKG}"
#endif

/* Specify version */
#ifndef RFC2045VER
#cmakedefine RFC2045VER "${RFC2045VER}"
#endif

/* The size of `double', as computed by sizeof. */
#ifndef SIZEOF_DOUBLE
#cmakedefine SIZEOF_DOUBLE ${SIZEOF_DOUBLE}
#endif

/* The size of `float', as computed by sizeof. */
#ifndef SIZEOF_FLOAT
#cmakedefine SIZEOF_FLOAT ${SIZEOF_FLOAT}
#endif

/* The size of `int', as computed by sizeof. */
#ifndef SIZEOF_INT
#cmakedefine SIZEOF_INT ${SIZEOF_INT}
#endif

/* The size of `int *', as computed by sizeof. */
#ifndef SIZEOF_INT_P
#cmakedefine SIZEOF_INT_P ${SIZEOF_INT_P}
#endif

/* The size of `long', as computed by sizeof. */
#ifndef SIZEOF_LONG
#cmakedefine SIZEOF_LONG ${SIZEOF_LONG}
#endif

/* The size of `long int', as computed by sizeof. */
#ifndef SIZEOF_LONG_INT
#cmakedefine SIZEOF_LONG_INT ${SIZEOF_LONG_INT}
#endif

/* The size of `long long', as computed by sizeof. */
#ifndef SIZEOF_LONG_LONG
#cmakedefine SIZEOF_LONG_LONG ${SIZEOF_LONG_LONG}
#endif

/* The size of `long long int', as computed by sizeof. */
#ifndef SIZEOF_LONG_LONG_INT
#cmakedefine SIZEOF_LONG_LONG_INT ${SIZEOF_LONG_LONG_INT}
#endif

/* The size of `short int', as computed by sizeof. */
#ifndef SIZEOF_SHORT_INT
#define SIZEOF_SHORT_INT ${SIZEOF_SHORT_INT}
#endif

/* The size of `SQLWCHAR', as computed by sizeof. */
#ifndef SIZEOF_SQLWCHAR
#define SIZEOF_SQLWCHAR ${SIZEOF_SQLWCHAR}
#endif

/* The Size Of` `void*', as computed by sizeof. */
#ifndef SIZEOF_VOIDP
#define SIZEOF_VOIDP ${SIZEOF_VOIDP}
#endif

/* The size of `void *', as computed by sizeof. */
#ifndef SIZEOF_VOID_P
#define SIZEOF_VOID_P ${SIZEOF_VOID_P}
#endif

/* The size of `wchar_t', as computed by sizeof. */
#ifndef SIZEOF_WCHAR_T
#define SIZEOF_WCHAR_T ${SIZEOF_WCHAR_T}
#endif

/* relocable objects */
#ifndef SO_EXT
#define SO_EXT "${SO_EXT}"
#endif

/* library search variable */
#ifndef SO_PATH
#ifdef __APPLE__
#define SO_PATH "DYLD_LIBRARY_PATH"
#elif _WIN32
#define SO_PATH "PATH"
#elif __unix__
#define SO_PATH "LD_LIBRARY_PATH"
#else
#define SO_PATH NULL
#endif
#endif

/* enable condor distributed execution, static compilation */
#ifndef SUPPORT_CONDOR
#cmakedefine SUPPORT_CONDOR "${SUPPORT_CONDOR}"
#endif

/* Define to 1 if your <sys/time.h> declares `struct tm'. */
#ifndef TM_IN_SYS_TIME
#cmakedefine TM_IN_SYS_TIME "${TM_IN_SYS_TIME}"
#endif

/* use bignums/rationals in YAP code. */
#if defined( __ANDROID__ ) && !defined(USE_GMP)
#define USE_GMP 1
#elif !defined(USE_GMP)
#define USE_GMP ${GMP_FOUND}
#endif

/* use Judy library for UDI indexing in YAP code. */
#ifndef USE_JUDY
#define USE_JUDY ${WITH_JUDY}
#endif


/* Use mmap in or-parallel copying */
#ifndef USE_SYSTEM_MMAP
#cmakedefine USE_SYSTEM_MMAP  ${WITH_SYSTEM_MMAP}
#endif

/* Whether daylight savings time offset is set via the altzone variable */
#ifndef USE_TIME_ALTZONE
#cmakedefine USE_TIME_ALTZONE ${USE_TIME_ALTZONE}
#endif

/* Whether daylight savings time offset is set via the tm_isdst member */
#ifndef USE_TIME_DAYLIGHT
#cmakedefine USE_TIME_DAYLIGHT ${USE_TIME_DAYLIGHT}
#endif

/* Whether time offset is specified via the tm_gmtoff member */
#ifndef USE_TIME_GMTOFF
#cmakedefine USE_TIME_GMTOFF ${USE_TIME_GMTOFF}
#endif

/* use the original YP malloc to implement the data-base.  */
#ifndef USE_YAP_MALLOC
#cmakedefine USE_YAP_MALLOC ${WITH_YAP_MALLOC}
#endif



/* Define to name of the UUID header file. */
#ifndef UUID_H
#cmakedefine UUID_H "${UUID_H}"
#endif

/* Define WORDS_BIGENDIAN to 1 if your processor stores words with the most
significant byte first (like Motorola and SPARC, unlike Intel). */
#if defined AC_APPLE_UNIVERSAL_BUILD
# if defined __BIG_ENDIAN__
#  define WORDS_BIGENDIAN 1
# endif
#else
# ifndef WORDS_BIGENDIAN
# define WORDS_BIGENDIAN 0
#ifndef WORDS_BIGENDIAN
#
# endif
#endif
#endif

/* architecture */
#ifndef YAP_ARCH
#define YAP_ARCH     "${YAP_ARCH}"
#endif

#ifndef YAP_PL_SRCDIR
#define YAP_PL_SRCDIR "${PROJECT_SOURCE_DIR}/pl"
#endif


/* YAP_IS_MOVABLE */
#ifndef YAP_IS_MOVABLE
#cmakedefine YAP_IS_MOVABLE "${YAP_IS_MOVABLE}"
#endif

#ifndef YAP_TIMESTAMP
#define YAP_TIMESTAMP ${YAP_TIMESTAMP}
#endif

/* yap version as a term */
#ifndef YAP_TVERSION
#define YAP_TVERSION "yap(${YAP_MAJOR_VERSION},${YAP_MINOR_VERSION},${YAP_PATCH_VERSION},0)"
#endif

/* what timezone we are in */
#ifndef YAP_VAR_TIMEZONE
#define YAP_VAR_TIMEZONE ${YAP_VAR_TIMEZONE}
#endif

/* yap compiled at */
#ifndef YAP_COMPILED_AT
#define YAP_COMPILED_AT "${YAP_TIMESTAMP}@${YAP_SITE}"
#endif



/* name of YAP instaii */
#ifndef YAP_ROOTDIR
#define YAP_ROOTDIR "${YAP_ROOTDIR}"
#endif

/* name of YAP binaries */
#ifndef YAP_BINDIR
#define YAP_BINDIR "${YAP_BINDIR}"
#endif

/* name of YAP headers */
#ifndef YAP_INCLUDEDIR
#define YAP_INCLUDEDIR "${YAP_INCLUDEDIR}"
#endif

/* name of YAP library */
#ifndef YAP_LIBDIR
#define YAP_LIBDIR "${YAP_LIBDIR}"
#endif

/* name of YAP DLL library */
#ifndef YAP_DLLDIR
#define YAP_DLLDIR "${YAP_LIBDIR}/Yap"
#endif

/* run-time boot */
#ifndef YAP_INPUT_STARTUP
#define YAP_INPUT_STARTUP "${YAP_DLLDIR}/${YAP_STARTUP}"
#endif

/* init-time boot */
#ifndef YAP_OUTPUT_STARTUP
#define YAP_OUTPUT_STARTUP "${CMAKE_BINARY_DIR}/${YAP_STARTUP}"
#endif

/* name of YAP JIT library */
#ifndef YAP_YAPJITLIB
#define YAP_YAPJITLIB "${YAP_YAPJITLIB}"
#endif

#ifndef YAP_SHAREDIR
#define YAP_SHAREDIR  "${YAP_DATADIR}"
#endif

/* name of YAP PL library */
#ifndef YAP_PLDIR
#define YAP_PLDIR "${YAP_PLDIR}"
#endif

/* name of Commons library */
#ifndef YAP_COMMONSDIR
#define YAP_COMMONSDIR "${YAP_DATADIR}/PrologCommmons"
#endif


/* run-time boot */
#ifndef YAP_SOURCEBOOT
#define YAP_SOURCEBOOT "${CMAKE_SOURCE_DIR}/pl/boot.yap"
#endif

/* init-time boot */
#ifndef YAP_BOOTSTRAP
#define YAP_BOOTSTRAP "${YAP_PLDIR}/pl/boot.yap"
#endif



/* HP-UX old socket stuff */
#ifndef _XOPEN_SOURCE
#cmakedefine _XOPEN_SOURCE "${_XOPEN_SOURCE}"
#endif

/* HP-UX old socket stuff */
#ifndef _XOPEN_SOURCE_EXTENDED
#cmakedefine _XOPEN_SOURCE_EXTENDED "${_XOPEN_SOURCE_EXTENDED}"
#endif


/* Define to empty if `const' does not conform to ANSI C. */
#ifndef const
#cmakedefine const "${const}"
#endif

/* Define to `__inline__' or `__inline' if that's what the C compiler
calls it, or to nothing if 'inline' is not supported under any name.  */
#ifndef __cplusplus
#ifndef inline
#cmakedefine inline "${inline}"
#endif
#endif

/* Define to `long int' if <sys/types.h> does not define. */
#ifndef off_t
#cmakedefine off_t "${off_t}"
#endif

/* Define to `int' if <sys/types.h> does not define. */
#ifndef pid_t
#cmakedefine pid_t "${pid_t}"
#endif

#ifndef MAXPATHLEN
#if defined(PATH_MAX)
#define MAXPATHLEN PATH_MAX
#else
#define MAXPATHLEN 1024
#endif
#endif

#if YAPOR
#ifndef  USE_DL_MALLOC
#define USE_DL_MALLOC 1
#endif
#else
/* use the OS malloc or some other external library to implement the data-base
*/
#ifndef USE_SYSTEM_MALLOC
#define USE_SYSTEM_MALLOC ${WITH_SYSTEM_MALLOC}
#endif
#endif

#ifndef HAVE_STRLCPY
#define strlcpy(X,Y,Z) strcpy(X,Y)
#endif

//#define DEBUG_MALLOC 1
#if DEBUG_MALLOC
#define malloc(sz) my_malloc(sz)
#define realloc(pt, sz) my_realloc(pt,sz)
#define free(pt) my_free(pt)
#endif

#ifdef _WIN32
#ifndef  __WINDOWS__
#define __WINDOWS__ 1
#endif
#endif

#include "YapTermConfig.h"

#endif
