set (CPACK_PACKAGE_NAME YAP)
set (CPACK_PACKAGE_VENDOR Artur)

set (CPACK_PACKAGE_VERSION_MAJOR 6)
set (CPACK_PACKAGE_VERSION_MINOR 3)
set (CPACK_PACKAGE_VERSION_PATCH 6)

set (CPACK_PACKAGE_DESCRIPTION_SUMMARY "YAP CPACK NSIS")

set (CPACK_PACKAGE_DESCRIPTION_FILE "README.md")

#set (CPACK_INSTALL_CMAKE_PROJECTS Release)
set (CPACK_INSTALLED_DIRECTORIES "C:\\Program Files\\YAP" .)

set (CPACK_PACKAGE_FILE_NAME ${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION}-${CPACK_SYSTEM_NAME})

set (CPACK_RESOURCE_FILE_LICENSE "C:\\Program Files\\YAP\\Artistic")