/*--------------------------------------------------------------------------
* This file is autogenerated from rconfig.h.cmake 
* during the cmake configuration of your project. If you need to make changes
* edit the original file NOT THIS FILE.
* --------------------------------------------------------------------------*/
#ifndef R4YAPCONFIG_H
#define R4YAPCONFIG_H

/* Define to 1 if you have the <alloca.h> header file. */
#ifndef HAVE_RINTERNALS_H
#cmakedefine HAVE_RINTERNALS_H ${HAVE_RINTERNALS_H}
#endif


/* Define to 1 if you have the <alloca.h> header file. */
#ifndef HAVE_R_EMBEDDED_H
#cmakedefine HAVE_R_EMBEDDED_H ${HAVE_R_EMBEDDED_H}
#endif

/* Define to 1 if you have the <alloca.h> header file. */
#ifndef HAVE_R_INTERFACE_H
#cmakedefine HAVE_R_INTERFACE_H ${HAVE_R_INTERFACE_H}
#endif
/* Define to 1 if you have the <alloca.h> header file. */
#ifndef HAVE_R_H
#cmakedefine HAVE_R_H ${HAVE_R_H}
#endif


#endif // R4YAPCONFIG_H
  
