#!/bin/bash

## ================================================================
## Logtalk - Open source object-oriented logic programming language
## Release 2.30.7
##
## Copyright (c) 1998-2007 Paulo Moura.  All Rights Reserved.
## ================================================================

echo "Removing menu entries for some of the Logtalk integration scripts..."

if test -x /usr/bin/update-menus; then
	update-menus
fi

echo ""
echo "You have succesfully uninstalled Logtalk!"
echo ""
