#!/bin/bash

## ================================================================
## Logtalk - Open source object-oriented logic programming language
## Release 2.30.7
##
## Copyright (c) 1998-2007 Paulo Moura.  All Rights Reserved.
## ================================================================

echo ""
echo "Installed Logtalk on \"/usr/share\"."

chown -f -R -L root:root /usr/share/logtalk

echo ""
echo "Installing and registering Logtalk online documentation..."

if [ "$1" = configure ]; then
	if which install-docs >/dev/null 2>&1; then
		install-docs -i /usr/share/doc-base/logtalk-docs
	fi
fi

chown -f -R -L root:root /usr/share/doc/logtalk

echo "Adding menu entries for some of the Logtalk integration scripts..."

if test -x /usr/bin/update-menus; then
	update-menus
fi

echo
echo "Links to the \"cplgtdirs\", \"lgt2pdf\", \"lgt2html\", and \"lgt2xml\" scripts have"
echo "been created on \"/usr/bin\"."
echo
echo "The following integration scripts are installed for running Logtalk"
echo "with selected back-end Prolog compilers:"
echo
echo "  B-Prolog:       bplgt       (first run must use sudo)"
echo "  CIAO:           ciaolgt     (first run must use sudo)"
echo "  CxProlog:       cxlgt"
echo "  ECLiPSe:        eclipselgt"
echo "  GNU Prolog:     gplgt"
echo "  K-Prolog:       plclgt"
echo "  Qu-Prolog:      qplgt"
echo "  SICStus Prolog: sicstuslgt"
echo "  SWI-Prolog:     swilgt"
echo "  XSB:            xsblgt      (first run must use sudo)"
echo "  XSB (MT):       xsbmtlgt    (first run must use sudo)"
echo "  YAP:            yaplgt"
echo
echo "The Prolog integration scripts can be found on \"/usr/bin\"."
echo "Make sure that the Prolog compilers are properly installed and available"
echo "on your execution path."
echo
echo "Users should run the \"cplgtdirs\" shell script once before using the"
echo "integration scripts."
echo
echo "If you get an unexpected failure when using one of the Prolog integration"
echo "scripts, consult see the \"/usr/share/logtalk/configs/NOTES.txt\" file"
echo "for compatibility notes."
echo
echo "Logtalk basic installation completed."
echo
