#!/bin/bash

## ================================================================
## Logtalk - Open source object-oriented logic programming language
## Release 2.30.2
##
## Copyright (c) 1998-2007 Paulo Moura.  All Rights Reserved.
## ================================================================

echo ""
echo "Uninstalling and de-registering Logtalk online documentation..."

if [ "$1" = remove -o "$1" = upgrade ]; then
	if which install-docs >/dev/null 2>&1; then
		install-docs -r logtalk-docs
	fi
fi

echo ""
echo "Removing Logtalk integration and documentation scripts..."

rm -rf /usr/share/logtalk/bin
