include(CheckIncludeFiles)
include(CheckFunctionExists)
include(CheckPrototypeExists)

# Test signal handler return type (mimics AC_TYPE_SIGNAL)
include(TestSignalType) #check if this is really needed as c89 defines this as void

# Test standard headers (mimics AC_HEADER_STDC)
include(TestSTDC)

#
# Check header files
#
check_include_files(alloca.h HAVE_ALLOCA_H)
# check_include_files(arpa/inet.h HAVE_ARPA_INET_H)
check_include_files(ctype.h HAVE_CTYPE_H)
check_include_files(crypt.h HAVE_CRYPT_H)
check_include_files(direct.h HAVE_DIRECT_H)
check_include_files(dirent.h HAVE_DIRENT_H)
# check_include_files(dlfcn.h HAVE_DLFCN_H)
check_include_files(errno.h HAVE_ERRNO_H)
check_include_files(execinfo.h HAVE_EXECINFO_H)
check_include_files(fcntl.h HAVE_FCNTL_H)
check_include_files(fenv.h HAVE_FENV_H)
check_include_files(float.h HAVE_FLOAT_H)
check_include_files(fpu_control.h HAVE_FPU_CONTROL_H)
check_include_files(ieeefp.h HAVE_IEEEFP_H)
check_include_files(io.h HAVE_IO_H)
check_include_files(limits.h HAVE_LIMITS_H)
check_include_files(locale.h HAVE_LOCALE_H)
# check_include_files(mach-o/dyld.h HAVE_MACH_O_DYLD_H)
check_include_files(malloc.h HAVE_MALLOC_H)
check_include_files(math.h HAVE_MATH_H)
check_include_files(memory.h HAVE_MEMORY_H)
# check_include_files(netdb.h HAVE_NETDB_H)
# check_include_files(netinet/in.h HAVE_NETINET_IN_H)
check_include_files(netinet/tcp.h HAVE_NETINET_TCP_H)
check_include_files(pwd.h HAVE_PWD_H)
# check_include_files(regex.h HAVE_REGEX_H)
check_include_files(siginfo.h HAVE_SIGINFO_H)
check_include_files(signal.h HAVE_SIGNAL_H)
check_include_files(stdarg.h HAVE_STDARG_H)
check_include_files(stdint.h HAVE_STDINT_H)
check_include_files(string.h HAVE_STRING_H)
# check_include_files(stropts.h HAVE_STROPTS_H)
# check_include_files(sys/conf.h HAVE_SYS_CONF_H)
check_include_files(sys/dir.h HAVE_SYS_DIR_H)
check_include_files(sys/file.h HAVE_SYS_FILE_H)
check_include_files(sys/mman.h HAVE_SYS_MMAN_H)
check_include_files(sys/ndir.h HAVE_SYS_NDIR_H)
check_include_files(sys/param.h HAVE_SYS_PARAM_H)
check_include_files(sys/resource.h HAVE_SYS_RESOURCE_H)
check_include_files(sys/select.h HAVE_SYS_SELECT_H)
check_include_files(sys/shm.h HAVE_SYS_SHM_H)
# check_include_files(sys/socket.h HAVE_SYS_SOCKET_H)
check_include_files(sys/stat.h HAVE_SYS_STAT_H)
check_include_files(sys/time.h HAVE_SYS_TIME_H)
check_include_files(sys/times.h HAVE_SYS_TIMES_H)
check_include_files(sys/types.h HAVE_SYS_TYPES_H)
check_include_files(sys/ucontext.h HAVE_SYS_UCONTEXT_H)
# check_include_files(sys/un.h HAVE_SYS_UN_H)
check_include_files(sys/wait.h HAVE_SYS_WAIT_H)
check_include_files(time.h HAVE_TIME_H)
check_include_files(unistd.h HAVE_UNISTD_H)
check_include_files(utime.h HAVE_UTIME_H)
check_include_files(wctype.h HAVE_WCTYPE_H)
#check_include_files(winsock.h HAVE_WINSOCK_H)
#check_include_files(winsock2.h HAVE_WINSOCK2_H)

#
# Check Function Exists
#
check_function_exists(_NSGetEnviron HAVE__NSGETENVIRON)
check_function_exists(_chsize_s HAVE__CHSIZE_S)
check_function_exists(access HAVE_ACCESS)
check_function_exists(acosh HAVE_ACOSH)
check_function_exists(alloca HAVE_ALLOCA)
check_function_exists(asinh HAVE_ASINH)
check_function_exists(atanh HAVE_ATANH)
# check_function_exists(chdir HAVE_CHDIR)
check_function_exists(clock HAVE_CLOCK)
check_function_exists(clock_gettime HAVE_CLOCK_GETTIME)
# check_function_exists(ctime HAVE_CTIME)
check_function_exists(dlopen HAVE_DLOPEN)
# check_function_exists(dup2 HAVE_DUP2)
check_function_exists(erf HAVE_ERF)
# check_function_exists(feclearexcept HAVE_FECLEAREXCEPT)
check_function_exists(fesettrapenable HAVE_FESETTRAPENABLE)
# check_function_exists(fgetpos HAVE_FGETPOS)
check_function_exists(finite HAVE_FINITE)
check_function_exists(fpclass HAVE_FPCLASS)
check_function_exists(ftime HAVE_FTIME)
check_function_exists(getcwd HAVE_GETCWD)
check_function_exists(getenv HAVE_GETENV)
# check_function_exists(gethostbyname HAVE_GETHOSTBYNAME)
# check_function_exists(gethostent HAVE_GETHOSTENT)
check_function_exists(gethostid HAVE_GETHOSTID)
check_function_exists(gethostname HAVE_GETHOSTNAME)
check_function_exists(gethrtime HAVE_GETHRTIME)
check_function_exists(getpagesize HAVE_GETPAGESIZE)
check_function_exists(getpwnam HAVE_GETPWNAM)
check_function_exists(getrlimit HAVE_GETRLIMIT)
check_function_exists(getrusage HAVE_GETRUSAGE)
check_function_exists(gettimeofday HAVE_GETTIMEOFDAY)
check_function_exists(getwd HAVE_GETWD)
check_function_exists(isatty HAVE_ISATTY)
check_function_exists(isnan HAVE_ISNAN)
check_function_exists(isinf HAVE_ISINF)
# check_function_exists(kill HAVE_KILL)
# check_function_exists(labs HAVE_LABS)
check_function_exists(link HAVE_LINK)
check_function_exists(lgamma HAVE_LGAMMA)
check_function_exists(localtime HAVE_LOCALTIME)
check_function_exists(lstat HAVE_LSTAT)
check_function_exists(mallinfo HAVE_MALLINFO)
check_function_exists(mbscoll HAVE_MBSCOLL)
check_function_exists(mbscasecoll HAVE_MBSCASECOLL)
check_function_exists(mbsnrtowcs HAVE_MBSNRTOWCS)
check_function_exists(memcpy HAVE_MEMCPY)
check_function_exists(memmove HAVE_MEMMOVE)
check_function_exists(mkstemp HAVE_MKSTEMP)
check_function_exists(mktemp HAVE_MKTEMP)
check_function_exists(nanosleep HAVE_NANOSLEEP)
check_function_exists(mktime HAVE_MKTIME)
check_function_exists(opendir HAVE_OPENDIR)
check_function_exists(putenv HAVE_PUTENV)
check_function_exists(rand HAVE_RAND)
check_function_exists(random HAVE_RANDOM)
check_function_exists(readlink HAVE_READLINK)
check_function_exists(regexec HAVE_REGEXEC)
check_function_exists(rename HAVE_RENAME)
check_function_exists(rint HAVE_RINT)
# check_function_exists(sbrk HAVE_SBRK)
check_function_exists(select HAVE_SELECT)
check_function_exists(setbuf HAVE_SETBUF)
check_function_exists(setitimer HAVE_SETITIMER)
check_function_exists(setlocale HAVE_SETLOCALE)
check_function_exists(setsid HAVE_SETSID)
# check_function_exists(setlinebuf HAVE_SETLINEBUF)
check_function_exists(sigaction HAVE_SIGACTION)
# check_function_exists(siggetmask HAVE_SIGGETMASK)
# check_function_exists(siginterrupt HAVE_SIGINTERRUPT)
check_function_exists(signal HAVE_SIGNAL)
check_function_exists(sigprocmask HAVE_SIGPROCMASK)
# check_function_exists(socket HAVE_SOCKET)
check_function_exists(stat HAVE_STAT)
# check_function_exists(strchr HAVE_STRCHR)
check_function_exists(strerror HAVE_STRERROR)
check_function_exists(stricmp HAVE_STRICMP)
check_function_exists(strlwr HAVE_STRLWR)
check_function_exists(strncat HAVE_STRNCAT)
check_function_exists(strncpy HAVE_STRNCPY)
# check_function_exists(strtod HAVE_STRTOD)
check_function_exists(time HAVE_TIME)
check_function_exists(times HAVE_TIMES)
check_function_exists(tmpnam HAVE_TMPNAM)
check_function_exists(usleep HAVE_USLEEP)
check_function_exists(utime HAVE_UTIME)
check_function_exists(vsnprintf HAVE_VSNPRINTF)
